### ISSUE TITLE
Build modified versoin of std

### ISSUE THREAD

**Issue by Yamakaky** [japaric/xargo#106]
I'm working on std (in `~/dev/rust/rust`), with a test crate in `/tmp/test`. I tried exporting `XARGO_RUST_SRC` and running `xargo build`, but it only build the test crate and not the modified `std`. How can I do that?

**Comment by japaric** [comment]
`XARGO_RUST_SRC` is ignored when you are using the nightly channel.

Try the [hack-for-cmr](https://github.com/japaric/xargo/tree/hack-for-cmr) branch.

```
$ cargo install --git https://github.com/japaric/xargo --branch hack-for-cmr
```

**Comment by Yamakaky** [comment]
Same problem...

**Comment by japaric** [comment]
Oh, wait. Are you trying to compile `std` for the host? That doesn't work right now. Xargo only builds sysroots when *cross* compiling (that's in the README)

**Comment by Yamakaky** [comment]
Oh, ok. Too bad.

**Comment by Yamakaky** [comment]
I get a lot of errors like
```
error: duplicate lang item in crate `core`: `debug_trait`.
  |
  = note: first defined in crate `core`.
```

**Comment by japaric** [comment]
@Yamakaky Please post more details. Contents of the crate (`src/main.rs`), Xargo.toml, the output of `xargo build -v` and whatever else you think may help.

**Comment by Yamakaky** [comment]
Xargo.toml
```
[target.x86_64-unknown-linux-gnu.dependencies.std]
features = []
```
Cargo.toml
```
[package]
name = "truc"
version = "0.1.0"
authors = ["yamakaky"]

[dependencies]
```
Output: https://0bin.net/paste/l12lhng4f7lA6Mu0#iLV1eE4mS2PfIA5FFQg6AEEdtS+UOBYQkv6bAg143Nm
main:
```
fn main() {
    panic!();
}
```
The rust source is updated to upstream/master.

**Comment by japaric** [comment]
This error comes from compiling `std` as a dylib, which is known to cause problems; see rust-lang/rust#36501. The interesting part is that you are getting a very different error from the one I saw when I reported rust-lang/rust#36501.

The workaround is to modify `std`'s Cargo.toml like this:

``` diff
diff --git a/src/libstd/Cargo.toml b/src/libstd/Cargo.toml
index a3996ead36..07a6c9cd49 100644
--- a/src/libstd/Cargo.toml
+++ b/src/libstd/Cargo.toml
@@ -7,7 +7,6 @@ build = "build.rs"
 [lib]
 name = "std"
 path = "lib.rs"
-crate-type = ["dylib", "rlib"]

 [dependencies]
 alloc = { path = "../liballoc" }
```

This needs to be fixed in the rust-lang/rust repo so that this (`cargo build`ing `std`) works without having to modify `std` source. That's what rust-lang/rust#36501 is tracking.

**Comment by Yamakaky** [comment]
Ok, thanks
