### ISSUE TITLE
xargo as a library

### ISSUE THREAD

**Issue by oli-obk** [japaric/xargo#113]
I'd like to use `xargo` for `miri` to generate libstd and friends with full MIR. I don't want to cross compile `miri`, but only run it by giving it custom sysroots.

So currently we do some [crazy env var dance](https://github.com/solson/miri/blob/master/tests/compiletest.rs#L59-L66) to get the sysroot (on travis and otherwise), then invoke `compiletest` with that sysroot. What I would like to do is to call `xargo` to generate the targets for me and then give me some sysroot paths that I can forward to `compiletest`. For now I'm going to use `std::process::Command`, but it would certainly be more comfy to use `xargo` as a library when writing tests (in contrast to the regular `xargo` usage, where one (cross) compiles the project itself)

**Comment by japaric** [comment]
> So currently we do some crazy env var dance to get the sysroot

Doesn't `rustc --print sysroot` work for this case? That logic is retrieving rustc's sysroot AFAICT.

As for Xargo, the sysroot is `~/.xargo` for cross compilation and `~/.xargo/HOST` for native compilation. Or replace `~/.xargo` with `$XARGO_HOME` if you are using that env variable.

> For now I'm going to use std::process::Command

Alternatively, you could call `xargo` on a no-op/empty Cargo project to generate the sysroot *before* you start running your tests.

> but it would certainly be more comfy to use xargo as a library when writing tests

Sorry, I don't feel compelled to maintian a Xargo library at this time. You are free to turn the current Xargo into a library on your side though.

**Comment by oli-obk** [comment]
> Doesn't rustc --print sysroot work for this case? That logic is retrieving rustc's sysroot AFAICT.

oh right, we already moved to that in a PR...

> Sorry, I don't feel compelled to maintian a Xargo library at this time. You are free to turn the current Xargo into a library on your side though.

Ok :) I'll do that.
