### ISSUE TITLE
Custom `panic_fmt` doesn't work

### ISSUE THREAD

**Issue by no1wudi** [japaric/xargo#115]
I'm using xargo v0.3.3,it seems that `panic_fmt` not be called when use macro `panic!()` or unwrap like this,when panicked,it falls into a infinite loop,nothing output from the serial port.
```rust
#![no_main]
#![no_std]
#![feature(lang_items)]
#![feature(collections)]

#[macro_use]
extern crate qx;
#[macro_use]
extern crate collections;
#[macro_use]
extern crate json;

use qx::prelude::*;

use qx::io::Read;
#[no_mangle]
pub fn main() {
    print!("Hello from Rust\n");
    let mut console = qx::fs::File::open("/dev/ttyS0").unwrap();
    let mut recv = String::new();
    console.read_to_string(&mut recv).unwrap();
    console.read_to_string(&mut recv).unwrap();
    print!("Recv : {}", recv);
}

use core::fmt::Arguments;
#[lang = "panic_fmt"]
extern "C" fn panic_fmt(fmt: Arguments, _: &(&'static str, u32)) -> ! {
    print!("Panic : {} \n", fmt);
    loop {

    }
}
```
And compile command: xargo build --target=thumbv7em-none-eabihf --release,running on nuttx rtos.

**Comment by japaric** [comment]
> use macro panic!() or unwrap like this,when panicked,it falls into a infinite loop

That sounds like `panic_fmt` *is* working but that your `print!` macro is not.

You could do a few things to verify this. For example, change your `panic_fmt` implementation to:

``` rust
#[lang = "panic_fmt"]
extern "C" fn panic_fmt(fmt: Arguments, _: &(&'static str, u32)) -> ! {
    foo();
    loop {

    }
}

#[inline(never)]
#[no_mangle]
fn foo() {}
```

And either use a debugger to see if calling `panic!` calls the `foo` function (breakpoint foo, then run, etc.). Or simply call `arm-none-eabi-objdump` on your executable and see if the `rust_begin_unwind` symbol (that's what `panic_fmt` gets renamed to) calls the `foo` symbol.

If you are *not* using Xargo to directly generate an executable and instead are using a build system (e.g. `make`) that turns your crate into an static library and then runs a custom linker command to generate an executable from that, then that could be why `panic_fmt` is being ignored.

**Comment by no1wudi** [comment]
Thank you,my `print!` works well,I've got it that I leaved `rust_begin_unwind` as a empty function in my c port file.

**Comment by toothbrush7777777** [comment]
@no1wudi Try adding this to `Cargo.toml`:

```toml
[profile.debug]
panic = "abort"
[profile.release]
panic = "abort"
```

**Comment by no1wudi** [comment]
@toothbrush7777777 Thanks for your suggestion,but it still doesn't work

**Comment by japaric** [comment]
I'm having trouble visualizing the whole setup / build system.

> in my c port file.

What's this C file?

> I'm using xargo to directly generate an executable.

This doesn't make sense to me. If you are use Cargo to drive the whole thing (and you are not manually invoking the linker) then you should either (a) get a compile error if two or zero `panic_fmt` lang items appear in the dependency graph or (b) get a linker error if the `panic_fmt` (actually the `rust_begin_unwind` symbol) didn't make it to the final executable because of symbol visibility (i.e. the symbol was not global)

Shot in the dark: Does adding `#[no_mangle]` to the `panic_fmt` function help?

Other than that, I can't be of more help without a way to reproduce this.

**Comment by no1wudi** [comment]
I've already tried it adding `#[no_mangle]` .
And my `.cargo/config`
[target.thumbv7em-none-eabihf]
rustflags = [
    "-C", "link-arg=-Tlinker.ld",
    "-C", "link-arg=-nostartfiles",
    "-C", "link-arg=--entry=__start",
    "-C", "link-arg=-Llibs",
    "-C", "link-arg=-mfloat-abi=hard",
    "-C", "link-arg=-nodefaultlibs",
    "-C", "link-arg=-Wl,--start-group",
    "-C", "link-arg=-lapps",  //Nuttx's app lib,but application entry point in Rust
    "-C", "link-arg=-lnuttx", // Nuttx's system lib
    "-C", "link-arg=/usr/lib/gcc/arm-none-eabi/4.9.3/armv7e-m/fpu/libgcc.a",
    "-C", "link-arg=-Wl,--end-group",
]
`Xargo.toml`
[target.thumbv7em-none-eabihf.dependencies]
collections = {}


My c port file just  used to avoid hard code some c macro in rust code like this:

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>

#ifndef __linux__
void rust_begin_unwind(void) {
  printf("Panicked!");  // It workes here,
}
#endif

void *port_mutex_create(void) {
  pthread_mutex_t *mutex = malloc(sizeof(pthread_mutex_t));
  if (mutex == NULL) {
    return mutex;
  }
  pthread_mutex_init(mutex, NULL);
  return mutex;
}

**Comment by toothbrush7777777** [comment]
@no1wudi Have you tried the following signature? It works for me in the latest compiler.

```rust
#[no_mangle]
#[lang = "panic_fmt"]
pub extern fn rust_begin_panic(msg: core::fmt::Arguments, file: &'static str, line: u32) -> ! {
    println!("Unhandled panic in {} on line {}:\r\n{}", file, line, msg);
    loop {}
}
```

**Comment by no1wudi** [comment]
@toothbrush7777777 @japaric Thanks,it works by adding `#[no_mangle]` after  `xargo clean` executed.
