### ISSUE TITLE
Better error message when `rust-src` is missing

### ISSUE THREAD

**Issue by jamesmunns** [japaric/xargo#124]
When installing `xargo` without `rust-src`, there is no notification that `rust-src` is necessary.

Instead this opaque error is shown:

```
➜  05-led-roulette git:(master) xargo build --target thumbv7em-none-eabihf
error: couldn't walk the sysroot
caused by: IO error for operation on /home/james/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src: No such file or directory (os error 2)
caused by: No such file or directory (os error 2)
note: run with `RUST_BACKTRACE=1` for a backtrace
```

You actually provide the helpful solution here: https://github.com/japaric/xargo/blob/c428cf1f3096f6832f8f0fc8ef337fa73454934a/src/rustc.rs#L90, however this isn't printed (I'm not familiar with how `chain_err` works/should work).

It would be nice to also show that same error message when the error condition is triggered  on line 74.

**Comment by djg** [comment]
I just ran into this issue too. Thanks for the help.
