### ISSUE TITLE
xargo rebuilds a random subset of dependencies on every build

### ISSUE THREAD

**Issue by oli-obk** [japaric/xargo#127]
This does not happen with cargo. Since it only happens on half the student's computers, and there's no pattern in their setups that can explain the difference, I cannot offer more information. All the students are using nightly-2017-03-28 and are compiling https://github.com/embed-rs/stm32f7-discovery

The moment a single file changes, dependencies are rebuild

Any ideas how to debug this?

**Comment by japaric** [comment]
> Any ideas how to debug this?

Set the env variable `RUST_LOG=cargo::ops::cargo_rustc::fingerprint` and run the Xargo command. Perhaps compare with other repo where the rebuild doesn't happen: an example from the discovery book or from the f3 crate.

**Comment by oli-obk** [comment]
We haven't been able to reproduce this anymore. Let's see what happens next April ;)
