### ISSUE TITLE
Xargo fails to copy nested directories

### ISSUE THREAD

**Issue by VictorKoenders** [japaric/xargo#128]
After not using xargo for a couple of months I tried updating it today and I get the following error:

    D:\Development\Personal\rust_stm32f103>xargo --verbose
    + "rustc" "--print" "sysroot"
    + "rustc" "--print" "target-list"
    + "cargo" "build" "--release" "--manifest-path" "C:\\Users\\VKOEND~1.INT\\AppData\\Local\\Temp\\xargo.L9kWwUhdnTlo\\Cargo.toml" "--target" "thumbv7em-none-eabihf" "-v" "-p" "core"
    Compiling core v0.0.0 (file:///C:/Users/vkoenders.INTRANET/.rustup/toolchains/nightly-x86_64-pc-windows-msvc/lib/rustlib/src/rust/src/libcore)
     Running `rustc --crate-name core C:\Users\vkoenders.INTRANET\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C metadata=ed3afdb7c1933857 -C extra-filename=-ed3afdb7c1933857 --out-dir C:\Users\VKOEND~1.INT\AppData\Local\Temp\xargo.L9kWwUhdnTlo\target\thumbv7em-none-eabihf\release\deps --target thumbv7em-none-eabihf -L dependency=C:\Users\VKOEND~1.INT\AppData\Local\Temp\xargo.L9kWwUhdnTlo\target\thumbv7em-none-eabihf\release\deps -L dependency=C:\Users\VKOEND~1.INT\AppData\Local\Temp\xargo.L9kWwUhdnTlo\target\release\deps -C link-arg=-Tstm32f103.ld -C link-arg=-nostartfiles --sysroot C:\Users\vkoenders.INTRANET\.xargo`
    Finished release [optimized] target(s) in 24.38 secs
    error: copying files from `C:\Users\vkoenders.INTRANET\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib/rustlib\x86_64-pc-windows-msvc\lib` to `C:\Users\vkoenders.INTRANET\.xargo\lib/rustlib\x86_64-pc-windows-msvc\lib` failed
    caused by: Access is denied. (os error 5)
    stack backtrace:
     0:     0x7ff6ca37090f - <no info>
     1:     0x7ff6ca371222 - <no info>
     2:     0x7ff6ca34a328 - <no info>
     3:     0x7ff6ca340a1d - <no info>
     4:     0x7ff6ca337fe6 - <no info>
     5:     0x7ff6ca34726c - <no info>
     6:     0x7ff6ca3441df - <no info>
     7:     0x7ff6ca3936a2 - <no info>
     8:     0x7ff6ca3929ca - <no info>
     9:     0x7ff6ca3a2429 - <no info>
    10:     0x7ff8e0578364 - BaseThreadInitThunk

The C:\Users\vkoenders.INTRANET\.xargo\lib/rustlib\x86_64-pc-windows-msvc\lib directory does get created and filled, so I'm not sure what's going wrong.

xargo 0.3.5
cargo 0.19.0-nightly (4e95c6b41 2017-03-23)
Windows 10 64 bit

I'm not sure where to start debugging or getting more info

**Comment by japaric** [comment]
Hmm, I'm don't have good suggestions. I'm not familiar with Windows error codes.

> C:\Users\vkoenders.INTRANET\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib/rustlib\x86_64-pc-windows-msvc\lib

Does this directory exist? I know that you can install toolchains for different hosts on Windows so maybe this copy operation is using the wrong host (the host that doesn't exist)?

As a shot in the dark you could try removing the whole Xargo directory: "C:\Users\vkoenders.INTRANET\.xargo". The directory layout has been extended (not changed) from previous versions so maybe some leftover from a previous version is making current Xargo see an invalid directory layout. .(Seems unlikely though)

Finally, is this "C:\Users\vkoenders.INTRANET\.xargo" on a network mount? Previous versions of Xargo had problems with rustup and $HOME being on different disks / mounts because it used symlinks. But today it uses a vanilla copy operation so I don't think this is the cause either :-/.

**Comment by VictorKoenders** [comment]
What I noticed is that:
1) xargo starts building the core libs with thumbv7em-none-eabihf, and this succeeds.
2) At this point the xargo/thumbv7em-none-eabihf/lib is filled with dll's and whatnot
3) xargo starts copying the msvc libs to the msvc folder
4) the msvc libs folder does get filled, but maybe it fails midway through

This is all after removing the old .xargo lib. If I don't remove the .xargo lib it just complains that the msvc lib doesn't exist. The lib directory does seem to get filled with some files, maybe it fails midway through? The folder is not on a network mount.

Is it intended behavior that it tries copying the msvc libs if you're building for thumbv7em-none-eabihf?

Maybe I should manually build a copy of xargo and add more debug lines to see where exactly it goes wrong, I'll look into that later.

**Comment by japaric** [comment]
> Is it intended behavior that it tries copying the msvc libs if you're building for thumbv7em-none-eabihf?

Yes, the Xargo sysroot must contain the host rlibs or you wouldn't be able to build build scripts.

> the msvc libs folder does get filled

Hmm, are contents the same as the one in `rustc --print sysroot`?

**Comment by VictorKoenders** [comment]
Initially, it copies everything except for a nested ```lib/VC``` folder.
If I copy that ```lib/VC``` folder, it throws away the ```lib``` folder and tries again, failing again to copy the VC folder.

There is also a ```.sentinel``` file, is that part of xargo?

The VC folder has the following files: ```libeay32MD.lib  libeay32MDd.lib  libeay32MT.lib  libeay32MTd.lib  ssleay32MD.lib  ssleay32MDd.lib  ssleay32MT.lib  ssleay32MTd.lib``` and a ```static``` folder that has a (presumably) static version of those libs.

**Comment by japaric** [comment]
> Initially, it copies everything except for a nested lib/VC folder.

That could be the problem then. Xargo is probably using the Windows equivalent of `cp foo bar` which only works for *files* so the operation fails when it tries to copy VC (since it's a folder).

**Comment by japaric** [comment]
> There is also a .sentinel file, is that part of xargo?

Oh, and yes. Xargo uses that as a file lock. There's probably also a `.hash` file around that Xargo uses to decide when the sysroot needs to be rebuilt.

**Comment by VictorKoenders** [comment]
After removing the VC subdirectory it builds fine.

... or rather it fails because my .ld file is messed up and it can't link the exceptions, but at least xargo works!

**Comment by japaric** [comment]
> After removing the VC subdirectory it builds fine.

I think ... you shouldn't have removed that. (I'm assuming that you removed it from `rustc --print sysroot`).

**Comment by VictorKoenders** [comment]
I moved it back afterwards. Trying to fix it now, it seems that the issue is here: https://github.com/japaric/xargo/blob/master/src/util.rs#L16

**Comment by japaric** [comment]
Right, you could do something like [this](https://github.com/rust-lang-nursery/rustup.rs/blob/master/src/rustup-utils/src/raw.rs#L331) or just plug in a crate like [this one](https://crates.io/crates/copy_dir). Whatever works for you, works for me 😄.

**Comment by japaric** [comment]
Xargo v0.3.6 has been released and includes a fix for this.

Thanks again @VictorKoenders for fixing this! ❤️

**Comment by VictorKoenders** [comment]
:heart:
