### ISSUE TITLE
Allow [replace] in Xargo.toml

### ISSUE THREAD

**Issue by cactorium** [japaric/xargo#131]
Is there a way to tell xargo to use patched versions of the source, or to replace sysroot dependencies with patched versions?

**Comment by gil0mendes** [comment]
Yes, there is a way. Check my [Xargo.toml](https://github.com/Infinity-OS/infinity/blob/master/Xargo.toml) to see how this works 😉

**Comment by cactorium** [comment]
Oh, thanks :)!
