### ISSUE TITLE
error: requires `freeze` lang_item

### ISSUE THREAD

**Issue by gil0mendes** [japaric/xargo#132]
Hey,

I have a problem when compiling the cross library with Xargo. This works well on macOS, but with a Linux Debian (or derived) I got the following error, that you can check on [Travis log](https://travis-ci.org/Infinity-OS/infinity/builds/224775421#L886).

Any idea of what is this?

**Comment by japaric** [comment]
> error: requires `freeze` lang_item

Well, you are missing the `freeze` lang item. I don't know if it's new as I have never implemented custom unwinding (it seems to be related to unwinding). But you can probably grep for `lang = "freeze"` in rust-lang/rust to find out what it's used for and what's its signature.

Alterantively, you could try changing panic-strategy to `abort` in you target specification file (`*-pulsar.json`).

**Comment by gil0mendes** [comment]
I already have the panic-strategy set to `about`. But I think maybe I'm using an old Rust repro version. Since this isn't related with the Xargo I will close this issue. Thanks man.
