### ISSUE TITLE
Building libtest for some reason, and causing errors

### ISSUE THREAD

**Issue by ids1024** [japaric/xargo#140]
Building with xargo is producing many errors like this, since for some reason `libtest` is being build with std, and libtest depends on libterm:

```
error: This node does not have a stability attribute
  --> /home/ian/Devel/src/redox/redox/rust/src/libterm/lib.rs:65:1
   |
65 | pub use terminfo::TerminfoTerminal;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I used `XARGO_RUST_SRC` to work around #135. This is possibly a peculiarity of Redox (although I don't know how, and it was previously working), but I expect it is affecting other platforms using `xargo` to build `std`.

This seems to fix it, but I doubt it's the correct solution:
```patch
diff --git a/src/sysroot.rs b/src/sysroot.rs
index 0b21611..d9d455b 100644
--- a/src/sysroot.rs
+++ b/src/sysroot.rs
@@ -315,7 +315,9 @@ impl Blueprint {
                     map.insert("path".to_owned(), Value::String(path));
                 }
 
-                blueprint.push(stage, k, map);
+                if k != "test" {
+                    blueprint.push(stage, k, map);
+                }
             } else {
                 Err(format!("Xargo.toml: target.{}.dependencies.{} must be \
                              a table",
```

**Comment by japaric** [comment]
> error: This node does not have a stability attribute

Hmm, I haven't seen that error before.

Can you provide more details about how you are using Xargo? e.g. what Xargo.toml are you using?

Are you using [stages](https://github.com/japaric/xargo/pull/116) to build libtest?

**Comment by ids1024** [comment]
> Are you using stages to build libtest?

Oh yes! Somehow I looked at the `Xargo.toml` (which I didn't write) without even noticing that libtest was specifically mentioned. I don't know how I could miss half of a four line file...

```toml
[dependencies.std]
features = ["panic_unwind"]

[dependencies.test]
stage = 1
```
This is the same as the one in the PR you linked to, so I presume it is correct (an it was previously working). Removing the last two lines of course fixes it.

**Comment by ids1024** [comment]
It looks like this is responsible: https://github.com/rust-lang/rust/commit/ab54f4b226639558ff46ea1f3e3f504aacef562d

Xargo should probably be passing `-Z force-unstable-if-unmarked` when it builds the sysroot.

**Comment by ids1024** [comment]
I would submit a PR, but I'm not sure where the `-Z` argument should be set, nor how to avoid breaking stable builds (the latest stable doesn't have this flag, and `-Z` doesn't work on stable as far as I know).

**Comment by japaric** [comment]
> I'm not sure where the -Z argument should be set

You can append it around [here](https://github.com/japaric/xargo/blob/3adb6e66df2dd1d88dacc6205013f7aa694640ee/src/sysroot.rs#L71).

> how to avoid breaking stable builds

Xargo doesn't support the stable and beta channels. You can't build core or std using the stable channel because all the crates in the std facade make use of unstable features.
