### ISSUE TITLE
Can't install xargo—invalid tar

### ISSUE THREAD

**Issue by Muhd** [japaric/xargo#148]
cargo install xargo --verbose
Failed to unpack package `xargo v0.3.8`

Caused by:
  invalid tar archive

**Comment by japaric** [comment]
Hmm, maybe a network error? It works fine on my side.

What OS are you using? It could be that. I'm using Linux.

**Comment by japaric** [comment]
If re-running `cargo install xargo` doesn't fetch a new Xargo crate you can remove your local copy with the following command (assuming Linux):

```
$ # the hash may look different
$ rm ~/.cargo/registry/cache/github.com-1ecc6299db9ec823/xargo-0.3.8.crate
```

**Comment by Muhd** [comment]
This is on windows. But it's fine, I just downloaded the binary manually and stuck in in the same directories as cargo. 

    On Thursday, June 8, 2017 3:08 AM, Jorge Aparicio <notifications@github.com> wrote:
 

 Hmm, maybe a network error? It works fine on my side.What OS are you using? It could be that. I'm using Linux.—

**Comment by Muhd** [comment]
But actually now I am getting the same error when I try to install "rayon-core" with xargo.

**Comment by Muhd** [comment]
I'm thinking this is a cargo issue not specific to xargo, but let me know if you think of anything to try.
