### ISSUE TITLE
Xargo doesn't warn the user about libcore needing a nightly Rust build to be compiled

### ISSUE THREAD

**Issue by HolmesSherlock** [japaric/xargo#153]
I used ` stable-x86_64-unknown-linux-gnu unchanged - rustc 1.18.0 (03fc9d622 2017-06-06)` to build a crate for a custom target. Xargo should build the `core` library even if it's not specified in the dependency. Unexpectedly, the `core` build didn't trigger at all. Instead, it complained of the crate `core` not being found.

    $ xargo build --target x86_64-unknown-none-gnu
    error[E0463]: can't find crate for `core`
    note: the `x86_64-unknown-none-gnu` target may not be installed

When I switched over to nightly (` nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.20.0-nightly (bf0a9e0b4 2017-07-10)`), to my utter surprise; Xargo triggered a `core` build.

I noticed after several hours that the issue is listed down already in the [Caveats](https://github.com/japaric/xargo) section. However, it'd be nice for Xargo to emit out more meaningful message.

**Comment by japaric** [comment]
This has been fixed in #168 and a warning message will be printed in this scenario when using Xargo v0.3.10+ (not yet released).
