### ISSUE TITLE
Xargo does not compile with latest nightly

### ISSUE THREAD

**Issue by antoyo** [japaric/xargo#159]
Hello.
I get the following error when trying to compile xargo with nightly.

```
error: doc comment not used by rustdoc
 --> src/errors.rs:1:1
  |
1 | error_chain!();
  | ^^^^^^^^^^^^^^^
  |
note: lint level defined here
 --> src/main.rs:1:9
  |
1 | #![deny(warnings)]
  |         ^^^^^^^^
  = note: #[deny(unused_doc_comment)] implied by #[deny(warnings)]
  = note: this error originates in a macro outside of the current crate

error: doc comment not used by rustdoc
 --> src/errors.rs:1:1
  |
1 | error_chain!();
  | ^^^^^^^^^^^^^^^
  |
  = note: this error originates in a macro outside of the current crate

error: aborting due to 2 previous errors

error: Could not compile `xargo`.

To learn more, run the command again with --verbose.
```
Thanks to fix this.

**Comment by lilianmoraru** [comment]
This was fixed in `error-chain 0.11.0-rc.2`: https://github.com/rust-lang-nursery/error-chain/commit/2b6e5f8a8f3383205f28ebab438ce1587182eeaa

This would need to wait for the `0.11` release of `error-chain`.
Did you make the warnings into errors or is this by default from `xargo`?

**Comment by lilianmoraru** [comment]
I just tried to compile it and it works for me(`git clone` + `cargo +nightly build`).
Could you please paste your `cargo` and `rustc` versions?
Mine are:
`cargo +nightly --version`: `cargo 0.22.0-nightly (7704f7b1f 2017-08-09)`
`rustc +nightly --version`: `rustc 1.21.0-nightly (df511d554 2017-08-14)`

**Comment by antoyo** [comment]
It works fine when installing with `cargo`.
It seems the error is in the [PKGBUILD](https://aur.archlinux.org/packages/xargo).
Thanks.

**Comment by lilianmoraru** [comment]
@antoyo My guess would be that `Arch` uses the stable `cargo` -> "stable" `xargo`(not using nightly, whatever you do?)?
