### ISSUE TITLE
intermittant IO error -- nothing produced in tempdir except empty src/lib.rs

### ISSUE THREAD

**Issue by mikedilger** [japaric/xargo#165]
If I change a target specificatiton JSON file, and then run xargo, and then revert everything back to a known working state.... the known working state doesn't work anymore.   I'm not mistyping these commands, I use a Makefile.

````
$ xargo build --target x86_64-unknown-os2018 --features="boot_multiboot2"
Finished release [optimized] target(s) in 0.0 secs
error: intermittent IO error while iterating directory `/tmp/xargo.7NQW9DkNHi8F/target/x86_64-unknown-os2018/release/deps`
caused by: IO error for operation on /tmp/xargo.7NQW9DkNHi8F/target/x86_64-unknown-os2018/release/deps: No such file or directory (os error 2)
caused by: No such file or directory (os error 2)
````

Note: similar behavior has been observed in closed issues where the user put a `.json` at the end of their `--target` argument.  I am not doing that.  Everything should be exactly as it was when it last worked, but it no longer works.  I've tried rebooting.  I've tried removing `~/.xargo/lib/rustlib/*`.  Neither helps.

**Comment by mikedilger** [comment]
Ok, maybe I've updated my rustc version, and nothing bad happened even though the target.json file was no longer valid for that rustc version... and I only became aware of this when the target.json file was again needed by xargo.

I think two things should happen here:  (1) cargo/rustc should not just exit with $?=0 and no output, and (2) xargo should get a different error message.   I could do (2), but if (1) was done, (2) shouldn't really be needed.

**Comment by mikedilger** [comment]
I'm not at all certain what is going on.  I can't find a working configuration (rust version and target specification that work together).

**Comment by japaric** [comment]
> If I change a target specificatiton JSON file, and then run xargo, and then revert everything back to a known working state.... the known working state doesn't work anymore.

I can't repro the problem from this statement. I tried:

``` console
$ cargo new --lib foo && cd $_
$ echo '#![no_std]' > src/lib.rs
$ rustc --target thumbv7m-none-eabi -Z unstable-options --print target-spec-json > foo.json
$ xargo build --target foo
$ vi foo.json # change 'vendor' from "" to "foo"
$ xargo build --target foo
$ vi foo.json # change 'vendor' from "foo" back to ""
$ xargo build --target foo
```

But I see no I/O problem. This was with:

``` console
$ rustc -V
rustc 1.21.0-nightly (c11f689d2 2017-08-29)

$ xargo -V
xargo 0.3.8
cargo 0.22.0-nightly (3d3f2c05d 2017-08-27)
```

Some ideas:

- Do you have RAM available? Do you have permissions to write to the `/tmp` directory?
- Do you have `CARGO_INCREMENTAL` enabled (set in the environment)? I have seen it cause some bizarre problems before.

When using Xargo with an invalid target specification I get:

``` console
$ xargo build --target foo
error: ~/tmp/foo/foo.json is not valid JSON
caused by: expected `,` or `}` at line 24 column 3
note: run with `RUST_BACKTRACE=1` for a backtrace
```

**Comment by mikedilger** [comment]
Thanks for your reply, tests and suggestions.

I found the problem.   I have a `.cargo/config` file with:
````
[build]
target-dir = "../../build/rust"
````

So the build output for sysroot is not ending up in the tmp directory.

Do you have any suggestions for how the main build output can be redirected, without breaking xargo's ability to build sysroot in the tmp directory?

**Comment by mikedilger** [comment]
It appears that CARGO_TARGET_DIR works.
