### ISSUE TITLE
Xargo not trying to compile std?

### ISSUE THREAD

**Issue by toolCHAINZ** [japaric/xargo#169]
Hi! Sorry if this is a dumb question (it might just be user error). I was playing around with Xargo, and I don't think that it's actually building `std` on my box (macOS). Am I doing something wrong? Here's the steps I've taken:

```bash
rustup component add rust-src
cargo install xargo
xargo new xargo_test --bin
cd xargo_test
echo "[target.x86_64-apple-darwin.dependencies.std]" > Xargo.toml 
echo "features = []" >> Xargo.toml
xargo build --release
```

The prints I see for the build step, however, make no mention of fetching or compiling `core`:
```
+ "rustc" "--print" "sysroot"
+ "cargo" "build" "--release" "-v"
   Compiling xargo_test v0.1.0 (file:///Users/me/Documents/rust_comparison/xargo_test)
     Running `rustc --crate-name xargo_test src/main.rs --crate-type bin --emit=dep-info,link -C opt-level=3 -C metadata=c744993201f20660 -C extra-filename=-c744993201f20660 --out-dir /Users/me/Documents/rust_comparison/xargo_test/target/release/deps -L dependency=/Users/me/Documents/rust_comparison/xargo_test/target/release/deps`
    Finished release [optimized] target(s) in 0.23 secs
```

If I try to compile for a target which I definitely don't have a prebuilt `std` package for, I get the usual `can't find crate for std` message that cargo gives.

Is there something I'm just missing on setting `xargo` up??

Thanks!

**Comment by japaric** [comment]
Are you *not* using the nightly channel? You have to use a nightly toolchain to build the sysroot.

**Comment by toolCHAINZ** [comment]
Same on nightly.

**Comment by toolCHAINZ** [comment]
For reference, this is what I was running:

```
rustup component add rust-src
cargo install xargo
xargo new xargo_test --bin
cd xargo_test
echo "[target.x86_64-apple-darwin.dependencies.std]" > Xargo.toml 
echo "features = []" >> Xargo.toml
xargo +nightly build --target x86_64-apple-darwin --release -v
```

Am I running this right?

**Comment by japaric** [comment]
Xargo doesn't understand `+nightly` (that's a rustup feature, not a Cargo one). You'll have to *switch* the toolchain (e.g. `rustup default nightly`); basically `rustc -V` on your project directory should print `rustc 1.NN.0-nightly ..`.

**Comment by toolCHAINZ** [comment]
Ahhhh, ok. That fixed it; confirmed user error, haha. Thanks for the help!
