### ISSUE TITLE
Passing link-args to the build of stdlib

### ISSUE THREAD

**Issue by roblabla** [japaric/xargo#179]
Hey, I'm trying to build a custom stdlib for a platform, but I'm getting link errors because it can't find `-lc` and `-lm`. I understand why the error happens, but I can't figure out how to make Xargo build `stdlib` (which is built as a dynamic library ?) with custom linker args. How can I tell xargo where to find them ? I tried `xargo build --target=mytarget -- -C link-args="-L/path/to/lib/folder"` but it still gives me the link error.

Full output : 
https://gist.github.com/roblabla/196b7021c1bd30542993da6bd089c6aa

**Comment by japaric** [comment]
> Xargo build stdlib (which is built as a dynamic library ?) 

I think std's Cargo.toml specifies that the library should be built as an .rlib (static library) *and* as a .dylib (dynamic library). If you don't want to build the .dylib (you probably are not going to need it -- unless you are building with `-C prefer-dynamic`) then you'll have to modify std's Cargo.toml to not build the dylib (remove "dylib" from crate-types).

---

The linker call contains:

> "-Bdynamic" "-l" "c" "-l" "m"  "-shared"

AIIU, this means the linker is going to for the shared version of libc and libm, so probably `libc.so` and `libm.so`. Are those files in the library search path you specified via `-L`?

If you meant to link those statically then you'll have to tweak the build scripts / source code of libstd. See `cargo:rustc-link-lib` for build scripts and `#[link(..)]` for the source code version of this setting.

**Comment by roblabla** [comment]
Just removing the `dylib` from libstd's crate-types did the trick ! Thanks a lot :)
