### ISSUE TITLE
Xargo seems not find my target

### ISSUE THREAD

**Issue by kinggoesgaming** [japaric/xargo#187]
I have a custom target for a libc that I am working on https://github.com/cirs/cirs
I have the spec here: https://github.com/cirs/cirs/blob/master/x86_64-unknown-linux-cirs.json at in the root of my project. But this error seems to pop up in Travis. https://travis-ci.org/cirs/cirs/builds/322038812

Mind with any help thanks :)

**Comment by japaric** [comment]
duplicate of #186
