### ISSUE TITLE
Issues with spaces in sysroot path (e.g., Windows user accounts containing spaces)

### ISSUE THREAD

**Issue by AaronCoad** [japaric/xargo#206]
When using xargo build, the error "Multiple input filenames provided" is returned when the Windows user account contains a space as the folderpath isn't wrapped in double-quotes when passed to rustc --sysroot. In my case C:\Users\Aaron Coad\.xargo

On another Windows PC where there is no space within the user account, xargo build works successfully.

**Comment by AxelMontini** [comment]
With #221 this should be fixed (escaping using `%20` or `\ `)

**Comment by RalfJung** [comment]
`RUSTFLAGS` does not support any kind of escaping, I don't think that would help.

What could help though is to write a `.cargo` file instead of using an environment variable.

**Comment by ZeWaka** [comment]
This is still an issue.

**Comment by RalfJung** [comment]
This is a fundamental limitation in cargo: https://github.com/rust-lang/cargo/issues/6139

There's not much we can do about this on the xargo side, I am afraid.

**Comment by kupiakos** [comment]
So, it seems the solution is to switch `RUSTFLAGS` to `CARGO_ENCODED_RUSTFLAGS` when passing to `cargo`. Possibly switching based on the cargo version.

> If the problem is xargo setting `RUSTFLAGS` unconditionally then that can be fixed with the recently added feature of `CARGO_ENCODED_RUSTFLAGS`. This is Cargo's "fix" to the solution for xargo.

https://github.com/rust-lang/cargo/pull/10232#issuecomment-1009012141
