### ISSUE TITLE
Adjust expected Xargo.toml path if `--manifest-path` is passed

### ISSUE THREAD

**Issue by phil-opp** [japaric/xargo#215]
When a `--manifest-path` argument is passed, a weird situation occurs: Cargo reads the project configuration from the passed `Cargo.toml` path, but Xargo reads the configuration from the current directory. This leads to errors if the project at the passed path needs additional crates such as `alloc`.

To fix this, we could update the `Xargo.toml` location when `--manifest-path` is passed. Would you be willing to merge a PR for this?

**Comment by reuvenpo** [comment]
Is there a plan to implement this? I would like to be able to chanage the Xargo.toml path dynamically

**Comment by RalfJung** [comment]
Xargo is in maintenance mode. So unless someone shows up and submits a PR, this is unlikely to be implemented.

Did you have a look at `cargo -Zbuild-std`, the intended successor for xargo? See https://github.com/rust-lang/wg-cargo-std-aware.

**Comment by reuvenpo** [comment]
>unless someone shows up and submits a PR, this is unlikely to be implemented.

Ah, i see. fair enough, i suppose.

>Did you have a look at `cargo -Zbuild-std`

Unfortunately I'm using [an std that is maintained by a third party](https://github.com/apache/incubator-teaclave-sgx-sdk), but i can poke them to try and modernize their approach.

In any case, thanks for the quick reply!

**Comment by jethrogb** [comment]
@reuvenpo have you tried using the [SGX target](https://edp.fortanix.com) that's included in the Rust compiler? No need to use Xargo.

**Comment by reuvenpo** [comment]
Fortanix does not support compiling enclaves with strictly defined interfaces. We're building an enclave that is integrated in a larger application, implemented in a different language, and we want/need to use the enclave as a library. Part of our security model is having a very small attack surface on the enclave. 
([This has been a pretty successful approach so far](https://github.com/enigmampc/SecretNetwork), we just have a few small road bumps here and there which we've been working around.)

**Comment by priyasiddharth** [comment]
@RalfJung can this issue be closed now?

**Comment by RalfJung** [comment]
Ah yes, this was fixed by https://github.com/japaric/xargo/pull/312. Thanks :)
