### ISSUE TITLE
Unable to compile xargo on Windows

### ISSUE THREAD

**Issue by alashworth** [japaric/xargo#22]
D:\MinGW>cargo install xargo
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling log v0.3.6
   Compiling semver v0.1.20
   Compiling nom v1.2.3
   Compiling libc v0.2.12
   Compiling filetime v0.1.10
   Compiling bitflags v0.1.1
   Compiling rand v0.3.14
   Compiling memchr v0.1.11
   Compiling rustc-serialize v0.3.19
   Compiling num_cpus v0.2.12
   Compiling num-traits v0.1.32
   Compiling strsim v0.3.0
   Compiling tar v0.4.6
   Compiling aho-corasick v0.5.2
   Compiling semver v0.2.3
   Compiling tempdir v0.3.4
   Compiling unicode-normalization v0.1.2
   Compiling pkg-config v0.3.8
   Compiling gcc v0.3.28
   Compiling regex-syntax v0.3.3
   Compiling winapi v0.2.7
   Compiling miniz-sys v0.1.7
   Compiling cmake v0.1.17
   Compiling flate2 v0.2.14
   Compiling libgit2-sys v0.4.3
   Compiling libssh2-sys v0.1.37
   Compiling uuid v0.1.18
   Compiling matches v0.1.2
   Compiling rustc_version v0.1.7
   Compiling toml v0.1.30
   Compiling url v0.2.38
   Compiling unicode-bidi v0.2.3
   Compiling idna v0.1.0
   Compiling crossbeam v0.2.9
   Compiling url v1.1.1
   Compiling libz-sys v1.0.4
   Compiling winapi-build v0.1.1
   Compiling advapi32-sys v0.1.2
   Compiling kernel32-sys v0.2.2
   Compiling glob v0.2.11
Build failed, waiting for other jobs to finish...
error: failed to compile `xargo v0.1.3`, intermediate artifacts can be found at `C:\Users\ANDREW~1\AppData\Local\Temp\cargo-install.U56h6Jyln4o9`

Caused by:
  failed to run custom build command for `libssh2-sys v0.1.37`
Process didn't exit successfully: `C:\Users\ANDREW~1\AppData\Local\Temp\cargo-install.U56h6Jyln4o9\release\build\libssh2-sys-468c4b5ae90680be\build-script-build` (exit code: 101)
--- stdout
running: "cmake" "C:\Users\Andrew Ashworth\.cargo\registry\src\github.com-1ecc6299db9ec823\libssh2-sys-0.1.37\libssh2" "-G" "MSYS Makefiles" "-DCRYPTO_BACKEND=WinCNG" "-DZLIB_INCLUDE_DIR=/" "-DBUILD_SHARED_LIBS=OFF" "-DENABLE_ZLIB_COMPRESSION=ON" "-DCMAKE_INSTALL_LIBDIR=lib" "-DBUILD_EXAMPLES=OFF" "-DBUILD_TESTING=OFF" "-DCMAKE_INSTALL_PREFIX=C:\Users\ANDREW~1\AppData\Local\Temp\cargo-install.U56h6Jyln4o9\release\build\libssh2-sys-468c4b5ae90680be\out" "-DCMAKE_C_FLAGS= -O0 -ffunction-sections -fdata-sections -m32" "-DCMAKE_CXX_FLAGS= -O0 -ffunction-sections -fdata-sections -m32" "-DCMAKE_BUILD_TYPE=Release"
-- The C compiler identification is GNU 6.1.0
-- Check for working C compiler: D:/MinGW/bin/gcc.exe
-- Check for working C compiler: D:/MinGW/bin/gcc.exe -- broken
-- Configuring incomplete, errors occurred!
See also "C:/Users/Andrew Ashworth/AppData/Local/Temp/cargo-install.U56h6Jyln4o9/release/build/libssh2-sys-468c4b5ae90680be/out/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/Andrew Ashworth/AppData/Local/Temp/cargo-install.U56h6Jyln4o9/release/build/libssh2-sys-468c4b5ae90680be/out/build/CMakeFiles/CMakeError.log".

--- stderr
CMake Error at D:/apps/cmake/share/cmake-3.4/Modules/CMakeTestCCompiler.cmake:61 (message):
  The C compiler "D:/MinGW/bin/gcc.exe" is not able to compile a simple test
  program.

  It fails with the following output:

   Change Dir: C:/Users/Andrew Ashworth/AppData/Local/Temp/cargo-install.U56h6Jyln4o9/release/build/libssh2-sys-468c4b5ae90680be/out/build/CMakeFiles/CMakeTmp

  Run Build Command:"D:/MinGW/bin/make.exe" "cmTC_c5f16/fast"

  D:/MinGW/bin/make.exe -f CMakeFiles/cmTC_c5f16.dir/build.make
  CMakeFiles/cmTC_c5f16.dir/build

  make.exe[1]: Entering directory 'C:/Users/Andrew
  Ashworth/AppData/Local/Temp/cargo-install.U56h6Jyln4o9/release/build/libssh2-sys-468c4b5ae90680be/out/build/CMakeFiles/CMakeTmp'

  process_begin: CreateProcess(NULL, sh.exe -c "/D/apps/cmake/bin/cmake.exe
  -E cmake_echo_color --switch= --progress-dir=/C/Users/Andrew
  Ashworth/AppData/Local/Temp/cargo-install.U56h6Jyln4o9/release/build/libssh2-sys-468c4b5ae90680be/out/build/CMakeFiles/CMakeTmp/CMakeFiles
  --progress-num=1 Building C object
  CMakeFiles/cmTC_c5f16.dir/testCCompiler.c.obj", ...) failed.

  make (e=2): The system cannot find the file specified.

  make.exe[1]: **\* [CMakeFiles/cmTC_c5f16.dir/build.make:65:
  CMakeFiles/cmTC_c5f16.dir/testCCompiler.c.obj] Error 2

  make.exe[1]: Leaving directory 'C:/Users/Andrew
  Ashworth/AppData/Local/Temp/cargo-install.U56h6Jyln4o9/release/build/libssh2-sys-468c4b5ae90680be/out/build/CMakeFiles/CMakeTmp'

  make.exe: **\* [Makefile:126: cmTC_c5f16/fast] Error 2

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:40 (project)

thread 'main' panicked at '
command did not execute successfully, got: exit code: 1

build script failed, must exit now', C:\Users\Andrew Ashworth.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.17\src\lib.rs:463
note: Run with `RUST_BACKTRACE=1` for a backtrace.

Any ideas?

**Comment by alashworth** [comment]
Also, the build script depends on curl, which I happen to have on my path, but I don't think it's listed as a dependency anywhere.

**Comment by somemetricprefix** [comment]
Try to run the command from the MINGW shell providid by MSYS2.
This worked for me.

**Comment by alashworth** [comment]
Same problem, fresh install of MSYS2 for windows. If I have time I will look into it more.

**Comment by somemetricprefix** [comment]
Strange the problem for me clearly was this line:

    process_begin: CreateProcess(NULL, sh.exe -c "/D/apps/cmake/bin/cmake.exe -E cmake_echo_color --switch= --progress-dir=/C/Users/Andrew Ashworth/AppData/Local/Temp/cargo-install.U56h6Jyln4o9/release/build/libssh2-sys-468c4b5ae90680be/out/build/CMakeFiles/CMakeTmp/CMakeFiles --progress-num=1 Building C object CMakeFiles/cmTC_c5f16.dir/testCCompiler.c.obj", ...) failed.

The path is in the format `/D/something` instead of `D:\something`. It should work in the MSYS2 shell because it handles those paths. Maybe the whitespace in your name is what breaks it for you.

Furthermore I’d recommend to start the MSYS2 shell with "msys2_shell.cmd -mingw64 --full-path" so you can access your system $PATH variable.

**Comment by alashworth** [comment]
$ cargo install xargo
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling num-traits v0.1.32
   Compiling strsim v0.3.0
   Compiling matches v0.1.2
   Compiling pkg-config v0.3.8
   Compiling rustc-serialize v0.3.19
   Compiling libc v0.2.12
   Compiling rand v0.3.14
   Compiling num_cpus v0.2.13
   Compiling log v0.3.6
   Compiling semver v0.1.20
   Compiling num-integer v0.1.32
   Compiling tempdir v0.3.4
   Compiling winapi v0.2.7
   Compiling nom v1.2.3
   Compiling memchr v0.1.11
   Compiling aho-corasick v0.5.2
   Compiling winapi-build v0.1.1
   Compiling semver v0.2.3
   Compiling advapi32-sys v0.1.2
   Compiling kernel32-sys v0.2.2
   Compiling crossbeam v0.2.9
   Compiling filetime v0.1.10
   Compiling tar v0.4.6
   Compiling num-iter v0.1.32
   Compiling num v0.1.32
   Compiling unicode-bidi v0.2.3
   Compiling unicode-normalization v0.1.2
   Compiling utf8-ranges v0.1.3
   Compiling glob v0.2.11
   Compiling idna v0.1.0
   Compiling regex-syntax v0.3.3
   Compiling url v1.1.1
   Compiling uuid v0.1.18
   Compiling toml v0.1.30
   Compiling url v0.2.38
   Compiling gcc v0.3.28
   Compiling bitflags v0.1.1
   Compiling rustc_version v0.1.7
   Compiling curl-sys v0.1.34
   Compiling libz-sys v1.0.4
   Compiling cmake v0.1.17
   Compiling libssh2-sys v0.1.37
   Compiling libgit2-sys v0.4.3
Build failed, waiting for other jobs to finish...
error: failed to compile `xargo v0.1.3`, intermediate artifacts can be found at `C:\Users\ANDREW~1\AppData\Local\Temp\cargo-install.8K30ffLz15kW`

Caused by:
  failed to run custom build command for `curl-sys v0.1.34`
Process didn't exit successfully: `C:\Users\ANDREW~1\AppData\Local\Temp\cargo-install.8K30ffLz15kW\release\build\curl-sys-610964e655b3913b\build-script-build` (exit code: 101)
--- stdout
Couldn't find libcurl from pkgconfig ("Failed to run `\"pkg-config\" \"--libs\" \"--cflags\" \"libcurl\"`: The system cannot find the file specified. (os error 2)"), compiling it from source...
cargo:rustc-link-search=C:\Users\ANDREW~1\AppData\Local\Temp\cargo-install.8K30ffLz15kW\release\build\curl-sys-610964e655b3913b\out/lib
cargo:rustc-link-lib=static=curl
cargo:root=C:\Users\ANDREW~1\AppData\Local\Temp\cargo-install.8K30ffLz15kW\release\build\curl-sys-610964e655b3913b\out
cargo:include=C:\Users\ANDREW~1\AppData\Local\Temp\cargo-install.8K30ffLz15kW\release\build\curl-sys-610964e655b3913b\out/include
cargo:rustc-flags=-l ws2_32
OPT_LEVEL = Some("3")
PROFILE = Some("release")
TARGET = Some("i686-pc-windows-gnu")
debug=false opt-level=3
HOST = Some("i686-pc-windows-gnu")
TARGET = Some("i686-pc-windows-gnu")
TARGET = Some("i686-pc-windows-gnu")
HOST = Some("i686-pc-windows-gnu")
CC_i686-pc-windows-gnu = None
CC_i686_pc_windows_gnu = None
HOST_CC = None
CC = None
TARGET = Some("i686-pc-windows-gnu")
HOST = Some("i686-pc-windows-gnu")
CFLAGS_i686-pc-windows-gnu = None
CFLAGS_i686_pc_windows_gnu = None
HOST_CFLAGS = None
CFLAGS = None
running: "sh" "/c/Users/Andrew Ashworth/.cargo/registry/src/github.com-1ecc6299db9ec823/curl-sys-0.1.34/curl/configure" "--with-winssl" "--enable-static=yes" "--enable-shared=no" "--enable-optimize" "--prefix=C:\\Users\\ANDREW~1\\AppData\\Local\\Temp\\cargo-install.8K30ffLz15kW\\release\\build\\curl-sys-610964e655b3913b\\out" "--without-librtmp" "--without-libidn" "--without-libssh2" "--without-nghttp2" "--disable-ldap" "--disable-ldaps" "--disable-ftp" "--disable-rtsp" "--disable-dict" "--disable-telnet" "--disable-tftp" "--disable-pop3" "--disable-imap" "--disable-smtp" "--disable-gopher" "--disable-manual"
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether to enable debug build options... no
checking whether to enable compiler optimizer... yes
checking whether to enable strict compiler warnings... no
checking whether to enable compiler warnings as errors... no
checking whether to enable curl debug memory tracking... no
checking whether to enable hiding of library internal symbols... yes
checking whether to enable c-ares for DNS lookups... no
checking for path separator... :
checking for sed... /usr/bin/sed
checking for grep... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ar... /d/MinGW/bin/ar
checking for a BSD-compatible install... /usr/bin/install -c
checking for gcc... gcc.exe
checking whether the C compiler works... no

--- stderr
/c/Users/Andrew Ashworth/.cargo/registry/src/github.com-1ecc6299db9ec823/curl-sys-0.1.34/curl/configure: line 3506: test: /c/Users/Andrew: binary operator expected
/usr/bin/sed: can't read /c/Users/Andrew: No such file or directory
/usr/bin/sed: can't read Ashworth/.cargo/registry/src/github.com-1ecc6299db9ec823/curl-sys-0.1.34/curl/include/curl/curlver.h: No such file or directory
/c/Users/Andrew Ashworth/.cargo/registry/src/github.com-1ecc6299db9ec823/curl-sys-0.1.34/curl/configure: line 3808: cd: /c/Users/Andrew: No such file or directory
configure: error: in `/c/Users/ANDREW~1/AppData/Local/Temp/cargo-install.8K30ffLz15kW/release/build/curl-sys-610964e655b3913b/out/build':
configure: error: C compiler cannot create executables
See `config.log' for more details
thread 'main' panicked at 'assertion failed: t!(cmd . status (  )).success()', C:\Users\Andrew Ashworth\.cargo\registry\src\github.com-1ecc6299db9ec823\curl-sys-0.1.34\build.rs:142
stack backtrace:
   0:   0x460121 - <unknown>
   1:   0x4265fe - <unknown>
   2: 0x77b9dc2d - <unknown>
   3:   0x407762 - <unknown>


Problem appears to be that whitespaces in the PATH aren't being escaped properly.

**Comment by japaric** [comment]
> Problem appears to be that whitespaces in the PATH aren't being escaped properly.

This appears to be a known problem in the curl-sys crate (alexcrichton/curl-rust#110). No fix yet. :-/

**Comment by alashworth** [comment]
Yet another problem with compiling on Windows - the MinGW-w64 distro is not supported. 

configure:4134: $? = 0
configure:4123: gcc.exe -v >&5
Using built-in specs.
COLLECT_GCC=D:\MinGW\bin\gcc.exe
COLLECT_LTO_WRAPPER=d:/mingw/bin/../libexec/gcc/x86_64-w64-mingw32/6.1.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../src/configure --with-gmp=/c/temp/gcc/gmp --with-mpfr=/c/temp/gcc/mpfr --with-mpc=/c/temp/gcc/mpc --enable-languages=c,c++ --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --disable-multilib --prefix=/c/temp/gcc/dest --with-sysroot=/c/temp/gcc/dest --disable-libstdcxx-pch --disable-nls --disable-shared --disable-win32-registry --enable-checking=release --with-tune=haswell
Thread model: win32
gcc version 6.1.0 (GCC) 
configure:4134: $? = 0
configure:4123: gcc.exe -V >&5
gcc.exe: error: unrecognized command line option '-V'
gcc.exe: fatal error: no input files
compilation terminated.
configure:4134: $? = 1
configure:4123: gcc.exe -qversion >&5
gcc.exe: error: unrecognized command line option '-qversion'; did you mean '--version'?
gcc.exe: fatal error: no input files
compilation terminated.
configure:4134: $? = 1
configure:4153: checking whether the C compiler works
configure:4175: gcc.exe -O3 -ffunction-sections -fdata-sections -m32    conftest.c  >&5
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/lib/libmingw32.a when searching for -lmingw32
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/lib\libmingw32.a when searching for -lmingw32
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/lib/libmingw32.a when searching for -lmingw32
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmingw32
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/libgcc.a when searching for -lgcc
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0\libgcc.a when searching for -lgcc
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/libgcc.a when searching for -lgcc
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lgcc
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/lib/libmoldname.a when searching for -lmoldname
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/lib\libmoldname.a when searching for -lmoldname
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/lib/libmoldname.a when searching for -lmoldname
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmoldname
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/lib/libmingwex.a when searching for -lmingwex
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/lib\libmingwex.a when searching for -lmingwex
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/lib/libmingwex.a when searching for -lmingwex
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmingwex
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/lib/libmsvcrt.a when searching for -lmsvcrt
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/lib\libmsvcrt.a when searching for -lmsvcrt
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/lib/libmsvcrt.a when searching for -lmsvcrt
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmsvcrt
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/lib/libadvapi32.a when searching for -ladvapi32
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/lib\libadvapi32.a when searching for -ladvapi32
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/lib/libadvapi32.a when searching for -ladvapi32
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -ladvapi32
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/lib/libshell32.a when searching for -lshell32
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/lib\libshell32.a when searching for -lshell32
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/lib/libshell32.a when searching for -lshell32
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lshell32
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/lib/libuser32.a when searching for -luser32
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/lib\libuser32.a when searching for -luser32
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/lib/libuser32.a when searching for -luser32
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -luser32
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/lib/libkernel32.a when searching for -lkernel32
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/lib\libkernel32.a when searching for -lkernel32
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/lib/libkernel32.a when searching for -lkernel32
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lkernel32
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/lib/libmingw32.a when searching for -lmingw32
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/lib\libmingw32.a when searching for -lmingw32
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/lib/libmingw32.a when searching for -lmingw32
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmingw32
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/libgcc.a when searching for -lgcc
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0\libgcc.a when searching for -lgcc
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/libgcc.a when searching for -lgcc
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lgcc
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/lib/libmoldname.a when searching for -lmoldname
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/lib\libmoldname.a when searching for -lmoldname
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/lib/libmoldname.a when searching for -lmoldname
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmoldname
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/lib/libmingwex.a when searching for -lmingwex
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/lib\libmingwex.a when searching for -lmingwex
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/lib/libmingwex.a when searching for -lmingwex
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmingwex
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/lib/libmsvcrt.a when searching for -lmsvcrt
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/lib\libmsvcrt.a when searching for -lmsvcrt
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/lib/libmsvcrt.a when searching for -lmsvcrt
d:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmsvcrt
collect2.exe: error: ld returned 1 exit status
configure:4179: $? = 1
configure:4217: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "curl"
| #define PACKAGE_TARNAME "curl"
| #define PACKAGE_VERSION "-"
| #define PACKAGE_STRING "curl -"
| #define PACKAGE_BUGREPORT "a suitable curl mailing list: http://curl.haxx.se/mail/"
| #define PACKAGE_URL ""
| /* end confdefs.h.  */
| 
| int main (void)
| {
| 
|  ;
|  return 0;
| }
configure:4222: error: in `/c/Users/Andrew/AppData/Local/Temp/cargo-install.5FyrstpWcLyq/release/build/curl-sys-610964e655b3913b/out/build':
configure:4224: error: C compiler cannot create executables
See `config.log' for more details

MinGW-W64 is not a dual targeting compiler. If you pass -m32 to it it falls over and fails.

**Comment by japaric** [comment]
> This is triggered while compiling the curl-sys crate.

You should report this on the curl-sys [issue tracker](https://github.com/alexcrichton/curl-rust/issues). It's more likely this will get fixed that way :smile:.

> MinGW-W64 is not a dual targeting compiler. If you pass -m32 to it it falls over and fails. 

What target triple are you compiling for? (If you are not passing `--target` to `cargo build` check the "host" field of the output of `rustc -Vv`) Sounds like you are trying to cross compile to 32-bit on a 64-bit environment (?).

**Comment by alashworth** [comment]
You're right, I should probably report this on the curl-sys tracker. The host is x86_64-w64-mingw32. Curl should not be passing -m32 to MinGW in its config tests on a 64-bit system - it's assuming 32-bit MinGW.

**Comment by japaric** [comment]
FWIW, you can `cargo install xargo` on Windows if you use the `i686-pc-windows-msvc` toolchain (probably the `x86_64` variant also works). You can pick the host of your toolchain if you install it via [rustup](https://www.rustup.rs/); it now comes with a menu to configure the toolchain installation.

**Comment by japaric** [comment]
This should Just Work now. Xargo no longer depends on libssh2-sys. So closing.
