### ISSUE TITLE
How to do `--emit=obj`?

### ISSUE THREAD

**Issue by JasonKleban** [japaric/xargo#223]
I've tried `--emit=obj`, `-- --emit=obj` and 

```
[target.aarch64-raspi3-none-elf]
rustflags = [ "-C", "emit=obj" ]
```

with `xargo build` but either there seems to be no effect (all I get is `.rlib` output) or warnings like 

```
warning: unused manifest key: target.aarch64-raspi3-none-elf.rustflags
```

I think `xargo rustc ...` might support this, but then I don't think it knows to cross-compile libcore.

Maybe I've missed clear documentation but I've read and tried [a lot of things](https://stackoverflow.com/questions/51005145/cross-compiling-baremetal-rust-for-raspberry-pi-3-b-from-windows).

**Comment by japaric** [comment]
>  How to do `--emit=obj`? 

The [documentation](https://github.com/japaric/xargo#usage) says:

> xargo has the exact same CLI as cargo.

So, the same way as you would do with Cargo: `xargo rustc [--target $T] -- --emit=obj` / `cargo rustc [--target $T] -- --emit=obj`. Perhaps `cargo-rustc` is not well documented?

> warning: unused manifest key: target.aarch64-raspi3-none-elf.rustflags

This looks strange. Did you add the rustflags to Cargo.toml? They go in [.cargo/config](https://doc.rust-lang.org/cargo/reference/config.html).

> I think xargo rustc ... might support this, but then I don't think it knows to cross-compile libcore.

`xargo-rustc` does cross compile core.

``` console
$ cargo new --lib hello
$ cd hello
$ xargo rustc -- --emit=obj
   Compiling core v0.0.0 (file:///home/japaric/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore)
(..)
```

**Comment by JasonKleban** [comment]
Hmm, ok thanks for that info.  Good to know that `xargo rustc` and `xargo build` both know to cross-compile the core.

Here's what I tried now against https://github.com/JasonKleban/rust-rasp:

```
xargo build --release --target aarch64-raspi3-none-elf --verbose
```

or

```
xargo rustc --target aarch64-raspi3-none-elf -- --emit=obj --release --verbose
```

But either way I get `error: unknown codegen option: 'emit'` (for which google gives no results as a phrase):

```
C:\Users\Jason\Repos\rust-rasp>xargo build --release --target aarch64-raspi3-none-elf --verbose
+ "rustc" "--print" "sysroot"
+ "rustc" "--print" "target-list"
+ RUSTFLAGS="-C emit=obj --sysroot C:\\Users\\Jason\\.xargo -Z force-unstable-if-unmarked"
+ "cargo" "build" "--release" "--manifest-path" "C:\\Users\\Jason\\AppData\\Local\\Temp\\xargo.slcTUhRFKyvT\\Cargo.toml" "--target" "aarch64-raspi3-none-elf" "-v" "-p" "core"
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names -C emit=obj --sysroot
C:\Users\Jason\.xargo -Z force-unstable-if-unmarked --target aarch64-raspi3-none-elf --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro` (exit code: 1)
--- stderr
error: unknown codegen option: `emit`
```

**Comment by japaric** [comment]
> RUSTFLAGS="-C emit=obj"

This is wrong; the rustc flag is `--emit=obj` not `-C emit=obj`. (See `rustc --help` and `rustc -C help`)

If you are going to use `xargo-rustc` then you don't need to set the rustflags in .cargo/config (*unless* you want to generate an object file for every dependency) so remove it from .cargo/config.

> xargo rustc --target aarch64-raspi3-none-elf -- --emit=obj --release --verbose

This is also wrong. The correct command is `xargo rustc --target aarch64-raspi3-none-elf --release --verbose -- --emit=obj`. `--release` and `--verbose` are Cargo flags. Only rustc flags must appear after the `--`.

**Comment by JasonKleban** [comment]
Wow!  that's great, thanks!  With that I now have a `\target\aarch64-raspi3-none-elf\release\deps\rust_rasp-ed0c2377e0a7df81.o`, the only .o file in the output, that I assume is what I wanted and is ready for linking.  So then this case is closed.  Thanks!

I intend to investigate how to do the following still:

1. make xargo/cargo/rustc pick a static name for the .o file, like `rust_rasp.o` or `kernel.o`
1. change the architecture from aarch64 to arm so I can use the [GNU Arm Embedded Toolchain](https://developer.arm.com/open-source/gnu-toolchain/gnu-rm/downloads) linker.  I don't yet know of an aarch64 toolchain available for windows.

**Comment by JasonKleban** [comment]
I updated https://stackoverflow.com/questions/51005145/cross-compiling-baremetal-rust-for-raspberry-pi-3-b-from-windows with additional hangups.  I call your attention to it in case you think any of it is xargo related - obviously I don't know what I'm doing; this is my shotgun approach to debugging.
