### ISSUE TITLE
Do not require nightly

### ISSUE THREAD

**Issue by Ekleog** [japaric/xargo#225]
I've recently been told that setting the environment variable `RUSTC_BOOTSTRAP=1` makes a standard `rustc` build able to build nightly-only crates. Maybe this could be used to not require a nightly build for compiling libcore?

**Comment by janderholm** [comment]
I made a quick and dirty patch in xargo which set the environment variable and removed the warning print and it seems to work!

Since this is how rustc bootstrap does to build libstd I think it should be perfectly safe to do this.

**Comment by RalfJung** [comment]
See my comments in https://github.com/japaric/xargo/pull/275#issuecomment-586899567: I don't think we should do this, not unless the Rust Compiler team explicitly blesses us to do so. And I honestly doubt that will happen -- so, I am closing the issue as (likely) not actionable.
