### ISSUE TITLE
Broken with current nightly

### ISSUE THREAD

**Issue by RalfJung** [japaric/xargo#240]
xargo is broken again with the current nightly because a new "workspace" crate got added and has to be `[patch]`ed: `rustc-std-workspace-alloc`

**Comment by RalfJung** [comment]
Cc https://github.com/japaric/xargo/issues/227 @jethrogb

**Comment by RalfJung** [comment]
@japaric FWIW, this blocks getting Miri to work again. Also see https://github.com/japaric/xargo/issues/227#issuecomment-471032949: @jethrogb and me offered to do some basic xargo maintenance, review and merge PRs so that xargo's basic functionality can keep working until cargo can do the job (and there is no other tool that I know of that can build libstd -- cargo-xbuild can only build libcore and liballoc).  We just ask for your time this once more to get us into a position where we can do this in the future. :)

**Comment by japaric** [comment]
Sorry for the super slow response. I've been hard at work on my thesis and my e-mail / notifications have been piling up for a while.

@RalfJung @jethrogb I'll take you on that offer. I have just sent you an invite to become collaborators and co-owners of the crates.io crate. I think you know way better than me in which order to land the outstanding PRs.

re: miri breaking. iirc, miri only uses xargo to re-build the std facade so it includes MIR for everything. This is more of an infra question, I guess, but have you considered including MIR on all the std crates *only on nightly*? My vague understanding is that this should only increase the size of the rust-std components but, imo, that seems better than having a rustup component (miri-preview) depend on a tool (xargo) not owned  by the rust-lang org. Just my two cents.

**Comment by jethrogb** [comment]
@japaric Thanks. Can you also add us on crates.io?

**Comment by japaric** [comment]
@jethrogb I did via the crates.io web interface when I posted my last comment. Maybe that didn't work? I have just sent another invite using `cargo owner`.

**Comment by jethrogb** [comment]
Oh it did work, just need to navigate to https://crates.io/me/pending-invites. Thanks!

**Comment by jethrogb** [comment]
What's the status with the Travis integration on this repo? It looks like [there's some stuff there](https://travis-ci.org/japaric/xargo/builds) but it's not integrated with GitHub?

**Comment by japaric** [comment]
This repo uses https://bors.tech/ Builds on PRs are enabled in Travis but they won't run until `master` is added to [this list](https://github.com/japaric/xargo/blob/29c067e6e6c1bc428be4cc55b6221c418109c7da/.travis.yml#L51). `bors try` and `bors r+` should work though.

**Comment by jethrogb** [comment]
Can you setup branch protection on this repo like so: https://github.com/bors-ng/bors-ng/issues/576#issuecomment-452675169

**Comment by japaric** [comment]
@jethrogb you'll need to do `bors try` or `bors r+` first because bors doesn't show up in the list of status checks.

![20190507-230042](https://user-images.githubusercontent.com/5018213/57332997-2a0c8f80-711c-11e9-9ddf-27cafff181d9.png)

**Comment by japaric** [comment]
> you'll need to do bors try or bors r+

It needs to be `bors r+`. After the `bors try` in the other PR only travis shows in the list of status checks.

**Comment by RalfJung** [comment]
> miri only uses xargo to re-build the std facade so it includes MIR for everything. This is more of an infra question, I guess, but have you considered including MIR on all the std crates only on nightly?

Nightly is also fairly widely used, so I am not sure how happy people will be to make it bigger. Also, at least currently, the libstd-for-miri also has some other differences -- e.g., the `HashMap` in there avoids SIMD to be Miri-compatible.

**Comment by RalfJung** [comment]
We got a fix merged. :)

@jethrogb seems you already have some crates.io experience? Can you take care of making a release?

**Comment by jethrogb** [comment]
Published v0.3.14

**Comment by RalfJung** [comment]
Thanks!
