### ISSUE TITLE
Failed to compile 'rustc-std-workspace-alloc'

### ISSUE THREAD

**Issue by iulianR** [japaric/xargo#244]
Hello! With:
```
$ cat .cargo/config
[target.aarch64-unknown-linux-musl]
linker = "aarch64-openwrt-linux-gcc"
rustflags = ["-C", "target-feature=-crt-static"]
```
and
```
$ cat Xargo.toml 
[dependencies]
std = {}
```
Trying to build for `aarch64-unknown-linux-musl` gives:
```
$ xargo build --target aarch64-unknown-linux-musl --release
    Updating crates.io index
   Compiling libc v0.2.58
   Compiling compiler_builtins v0.1.16
   Compiling core v0.0.0 (/home/master/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore)
   Compiling cc v1.0.37
   Compiling unwind v0.0.0 (/home/master/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libunwind)
   Compiling rustc-std-workspace-alloc v1.0.0
error[E0463]: can't find crate for `std`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `rustc-std-workspace-alloc`.
warning: build failed, waiting for other jobs to finish...
error: build failed
error: `"cargo" "build" "--release" "--manifest-path" "/tmp/xargo.Snvllf1eSkON/Cargo.toml" "--target" "aarch64-unknown-linux-musl" "-p" "std"` failed with exit code: Some(101)
note: run with `RUST_BACKTRACE=1` for a backtrace
```
Any idea? Thanks

**Comment by jethrogb** [comment]
Are you using the latest version of xargo? It looks like there's a missing `[patch]` section, but that should be autogenerated.

**Comment by iulianR** [comment]
Yes, I am:
```
$ xargo --version
xargo 0.3.13
cargo 1.37.0-nightly (545f35425 2019-05-23)
```

**Comment by jethrogb** [comment]
The latest version is 0.3.14 actually.

**Comment by jethrogb** [comment]
I see we didn't do a release on GitHub. Also I think I pushed the version tag to the wrong remote, so that's fixed now. @japaric @RalfJung what's the release process?

**Comment by iulianR** [comment]
Yes, it seems to be working now. I did check `https://github.com/japaric/xargo/releases` to see what the latest release is though. Thank you!

**Comment by RalfJung** [comment]
> @japaric @RalfJung what's the release process?

I have no idea, I have never released any Rust project.^^

**Comment by jethrogb** [comment]
Oh I think it's just a matter of creating a tag, creating the release on GitHub, and then CI will automatically build & add the binaries!

**Comment by RalfJung** [comment]
Wow, nice.

I am not sure though if we really want to support distributing outside of crates.io? I mean I am fine with it if you are doing all the work. ;) But @iulianR I am wondering why you don't just `cargo install xargo`?

**Comment by iulianR** [comment]
I did `cargo install xargo` but never got around to using it and haven't `cargo install xargo --force` since then.
