### ISSUE TITLE
Trouble with crates duplicated between the sysroot and the project

### ISSUE THREAD

**Issue by RalfJung** [japaric/xargo#261]
See https://github.com/japaric/xargo/pull/217 for all the details: seems like sometimes there is a problem when a crate occurs both in the sysroot and as a dependency of the project itself. But unfortunately, @roblabla was not able to reproduce this problem, so it is not entirely clear what is really going on.

**Comment by RalfJung** [comment]
https://github.com/rust-lang/wg-cargo-std-aware/issues/34 might or might not be related.

**Comment by roblabla** [comment]
I have come across this bug again while updating a custom libstd to rust nightly 2019-11-25.

I'm currently working on making a minimal reproducer, but I'm very afraid that whatever reproducer I manage to create will be dependent on the rustc version used, making it hard to use as a xargo test...

**Comment by roblabla** [comment]
While investigating, I discovered that rust **does** inject custom metadata when building the libstd to avoid this very issue. See [here](https://github.com/rust-lang/rust/blob/73369f32621f6a844a80a8513ae3ded901e4a406/src/bootstrap/builder.rs#L888).

As such, I 100% think https://github.com/japaric/xargo/pull/217 is the proper fix here.

**Comment by roblabla** [comment]
https://github.com/roblabla/xargo-reproducer

**Comment by roblabla** [comment]
Unfortunately, this requires a fairly elaborate setup to reproduce (https://github.com/roblabla/xargo-reproducer/commit/abe5612ccb1c86588d991e5b3a8b8ba3b72c8c52 in my minimal reproducer, we need to inject a dependency in libcore). Not sure how I'd be able to recreate these conditions in a xargo smoke test.
