### ISSUE TITLE
Unlisted dependencies

### ISSUE THREAD

**Issue by thejpster** [japaric/xargo#27]
To build on Fedora 24, I needed to first install cmake and openssl-devel, which was unexpected. I think they were required for libssh2-sys.

Could these be added to the README?

**Comment by japaric** [comment]
> required for libssh2-sys.

Xargo uses Cargo as a library; that dependency pulls `libssh2-sys`. This is unfortunate because Xargo doesn't do anything SSH/git related.

> Could these be added to the README?

Sure! Mind sending a PR?

**Comment by thejpster** [comment]
#29

**Comment by japaric** [comment]
Xargo 0.2 doesn't depend on any system C library.
