### ISSUE TITLE
Enable branch protection

### ISSUE THREAD

**Issue by RalfJung** [japaric/xargo#271]
Currently it seems like while we usually use bors, we can still also push to master or merge a PR without bors. IMO it would make sense to enable GH branch protection to forbid side-stepping bors. But I don't have permissions for such a config change.

@jethrogb  @japaric what do you think?

**Comment by jethrogb** [comment]
These are the correct settings:
![image](https://user-images.githubusercontent.com/1132307/70397060-1e18e100-1a0f-11ea-8fc7-488481bf0f8c.png)

**Comment by japaric** [comment]
Configured branch protection as @jethrogb indicated

**Comment by RalfJung** [comment]
@japaric thanks!
