### ISSUE TITLE
Staged builds and local compiler-builtins

### ISSUE THREAD

**Issue by plauche** [japaric/xargo#273]
I'm encountering an interesting linking issue when building with a local version of `compiler_builtins`. I can't seem to set it to stage 0 in `Xargo.toml` because of the number of dependencies on `compiler_builtins` within `libstd` and it's dependencies. However, if I place `compiler_builtins` within stage 1, my local crate will be built, **along with** the version specified by `libstd`, and **only** the libstd version will be used in the final linking. This is an issue as it means any changes to my local `compiler_builtins` are not actually used. Is there a way to specify which version of `compiler_builtins` is used in the final linking?

**Comment by RalfJung** [comment]
Disclaimer: I never used xargo to build anything except for vanilla upstream libstd.

My first guess is: libstd will use the compiler-builtins specified in its Cargo.toml. Cargo doesn't just replace this by a random other crate with the same name, that would be a mess. If you want to have it depend on something else, that's what the `[patch]` section is for. See [the cargo docs](https://doc.rust-lang.org/cargo/reference/manifest.html#the-patch-section) for more details.

**Comment by jethrogb** [comment]
I think Ralf's right.

**Comment by plauche** [comment]
@RalfJung Thanks for the tip! 

I added this section to my `Xargo.toml` and that did the trick!
```
[patch.crates-io]
compiler_builtins = { path = "/path/to/compiler-builtins"}
```
