### ISSUE TITLE
Multiple matching crates error

### ISSUE THREAD

**Issue by plauche** [japaric/xargo#274]
Hi,

I've been working with `xargo` to do some cross compiling and have been having good luck, but recently ran into this `multiple matching crates for ...` error. It seems to be related to a dependency existing in my sysroot's build tree and my crate's build tree. In this case the dependency is `compiler-builtins`.

I have my `Xargo.toml` setup to provide `compiler-builtins` as a stage 1 dep and to patch any crates dependencies:
```
[target.thumbv7m-unknown-linux-uclibc.dependencies.std]
stage = 0

[target.thumbv7m-unknown-linux-uclibc.dependencies.compiler_builtins]
stage = 1

[patch.crates-io]
compiler_builtins = { path = "/vagrant/repos/compiler-builtins" }
libc = { path = "/vagrant/repos/libc" }
```

I can see in ` ~/.xargo/lib/rustlib/thumbv7m-unknown-linux-uclibc/lib/` that there are two built out versions, though in the build log they are both built from the same source. (Build log here - https://gist.github.com/plauche/37c7f9fd3dc7706cc42c931fd983a507.)
```
vagrant@ubuntu1804:/vagrant/repos/kubos$ ls -l ~/.xargo/lib/rustlib/thumbv7m-unknown-linux-uclibc/lib/libcompiler_builtins-*
-rw-rw-r-- 1 vagrant vagrant 478700 Jan 29 16:15 /home/vagrant/.xargo/lib/rustlib/thumbv7m-unknown-linux-uclibc/lib/libcompiler_builtins-3f560206bdedf7ac.rlib
-rw-rw-r-- 1 vagrant vagrant 321960 Jan 29 16:15 /home/vagrant/.xargo/lib/rustlib/thumbv7m-unknown-linux-uclibc/lib/libcompiler_builtins-3f560206bdedf7ac.rmeta
-rw-rw-r-- 1 vagrant vagrant 478612 Jan 29 16:15 /home/vagrant/.xargo/lib/rustlib/thumbv7m-unknown-linux-uclibc/lib/libcompiler_builtins-c7d2b98ed19ccc14.rlib
-rw-rw-r-- 1 vagrant vagrant 321909 Jan 29 16:15 /home/vagrant/.xargo/lib/rustlib/thumbv7m-unknown-linux-uclibc/lib/libcompiler_builtins-c7d2b98ed19ccc14.rmeta
```

I'm currently just deleting one set of the rlib/rmeta files and moving on in the process...but any direction on a more permanent solution would be great. I don't think `cargo-xbuild` is an option because I need to build a custom std.

I'm building with xargo 0.3.19 and rust 1.42.0-nightly.

More verbose build log here https://gist.github.com/plauche/9c7d733653e2db7439cc0e8969ea633e.

**Comment by RalfJung** [comment]
Isn't this the same as your previous https://github.com/japaric/xargo/issues/273 ? You shouldn't put `compiler_builtins` in a separate stage, xargo/cargo can already figure out this dependency. Just having the `patch` should be enough.

**Comment by RalfJung** [comment]
I guess the docs at https://github.com/japaric/xargo#creating-a-sysroot-with-custom-crates are outdated, but I also have no idea what the correct way to do this is these days -- I don't use xargo like that. So if someone could fix the README, that would be great. :D Cc @roblabla

**Comment by roblabla** [comment]
Right, so what's happening is that compiler-builtins is being built twice with different features - once as part of the std build (with the `rustc-dep-of-std` pulled from the liballoc Cargo.toml) and once as your stage 2, with the default features. This causes compiler-builtins to show up twice in your sysroot, which confuses cargo.

Note that this isn't necessarily a compiler-builtins specific issue. Care must be taken not to end up with any crate twice in the sysroot. I had similar problems with duplicated libcore due to similar features shenanigans ^^'.

Simply removing the stage 1 `compiler_builtins` should fix the error. I'll fix the README in a PR.

**Comment by plauche** [comment]
Hmm I must have added the stage 1 flag as part of my working through #273 but did not end up removing it after adding the patch. I was also working on a very simple program at the time, so this issue did not present itself. 

Removing the stage 1 fixed it! Thank you @RalfJung and @roblabla!!

**Comment by RalfJung** [comment]
@roblabla 
You wrote
> Simply removing the stage 1 compiler_builtins should fix the error. I'll fix the README in a PR.

Would be great if you could do that; I don't have the setup to check if a custom compiler_builtins would actually work. :)
