### ISSUE TITLE
Missing v0.3.20 release/tag in git?

### ISSUE THREAD

**Issue by jackcmay** [japaric/xargo#285]
Looks like v0.3.20 has been released to crates.io but there isn't a corresponding release/tag in git.  

The v0.3.19 git release shows it being updated a few hours ago, was maybe v0.3.20 re-released as v0.3.19?

**Comment by RalfJung** [comment]
No, it was just a few hours ago that I realized I had forgotten the 0.3.19 tag.^^

For 0.3.20, I remembered to create it, but then forgot to push it. I did that now. Thanks for the reminder!
