### ISSUE TITLE
Cannot build std for custom iOS target (arm64e)

### ISSUE THREAD

**Issue by edwinandrivet** [japaric/xargo#294]
Hello!
I hope this is the correct place for this issue since I'm a bit confused as to what is going on here. I've been trying to build for the iOS arm64e target and used the aarch64-apple-ios spec as the basis.
Here's my Xargo.toml:
```
[dependencies]
std = {}
```
I'm uploading the json file (as a txt file...) and logs to avoid an unreadable post:
[arm64e-apple-ios.json](https://github.com/japaric/xargo/files/4706413/arm64e-apple-ios.json.txt)

[log.txt](https://github.com/japaric/xargo/files/4706428/log.txt)

I tried checking in some src files but did not find anything "suspicious". The "nightly-arm64e-apple-ios" folder is just a copy of the x86_64 default install for the nightly (installed today) to be able to build std: nothing got changed there.
Might someone have an idea as to what I am possibly doing wrong?

Thanks in advance for your help!

**Comment by RalfJung** [comment]
Sorry, I know nothing about both iIOS and arm, so I cannot help here. Also xargo is in maintenance mode and deprecated.

Did you try [`cargo -Zbuild-std`](https://github.com/rust-lang/wg-cargo-std-aware)?

**Comment by edwinandrivet** [comment]
> Sorry, I know nothing about both iIOS and arm

Don't worry: that makes two of us. ;)

> Also xargo is in maintenance mode and deprecated.

I had read that thanks to the Readme but since my change seemed super basic/simple, I thought I just had missed an important step somehow.

> Did you try cargo -Zbuild-std?

I had not come across this and it looks interesting, I might be able to do something.

Thanks for your help and have a great day! I'm closing this issue.
