### ISSUE TITLE
Move away from travis-ci.org

### ISSUE THREAD

**Issue by RalfJung** [japaric/xargo#305]
Travis is shutting down their .org service and urging everyone to migrate to travis-ci.com. That is actually fairly easy, but can only be done by repository/organisation owners: on https://travis-ci.com/account/repositories, there's a "migrate" tab, and following that does everything one has to do.

@japaric I don't think anyone but you has the permissions to do this, so -- could you do that migration?

**Comment by japaric** [comment]
should work (?) now but note that macOS build jobs, unlike Linux, require "credits" so those jobs probably will not run

I guess there's also the option to move CI to GitHub Actions: https://github.com/actions-rs/meta

**Comment by RalfJung** [comment]
> I guess there's also the option to move CI to GitHub Actions: https://github.com/actions-rs/meta

Yeah, if someone puts in the work that would be great. But I doubt I'll find the time for that any time soon.

> should work (?) now but note that macOS build jobs, unlike Linux, require "credits" so those jobs probably will not run

Thanks! I'll make some test PR(s) to see what happens.

**Comment by RalfJung** [comment]
Fixed by https://github.com/japaric/xargo/pull/307
