### ISSUE TITLE
Cross compiling from Linux to Windows with disabled default features for std is giving error

### ISSUE THREAD

**Issue by Selyatin** [japaric/xargo#313]
I'm getting this error when trying to build with xargo with default std features off, I can compile just fine using normal cargo.
```
user@localhost:~/Documents/project> xargo build --release --target x86_64-pc-windows-gnu
error: couldn't copy /home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-pc-windows-gnu/lib/crt2.o to /home/user/.xargo/lib/rustlib/x86_64-pc-windows-gnu/lib/crt2.o
caused by: No such file or directory (os error 2)
note: run with `RUST_BACKTRACE=1` for a backtrace

```

**Comment by RalfJung** [comment]
The error is caused here:

https://github.com/japaric/xargo/blob/23c6fd206296548c179aa20e048f77626acf24fa/src/sysroot.rs#L67

You need to install the `x86_64-pc-windows-gnu` target, I think, to get those files? I am not an expert in Windows matters but I assume that xargo code was added for a reason.^^

> I can compile just fine using normal cargo.

How are you building the standard library using normal cargo?

**Comment by Selyatin** [comment]
I'm not building the standard library using normal cargo and I've x86_64-pc-windows-gnu installed, otherwise I wouldn't be able to compile it using standard cargo.

**Comment by RalfJung** [comment]
> I'm not building the standard library using normal cargo

Then what do you mean by "I can compile just fine using normal cargo"? I thought you meant building the standard library, now I am not sure.

>  I've x86_64-pc-windows-gnu installed

Hm, can you check if the file "crt2.o" exists anywhere in `/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-pc-windows-gnu`? It used to be at `/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-pc-windows-gnu/lib/crt2.o` but maybe it moved...

**Comment by RalfJung** [comment]
Looks like these days the files reside at
```
~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-pc-windows-gnu/lib/self-contained/crt2.o
~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-pc-windows-gnu/lib/self-contained/dllcrt2.o
~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-pc-windows-gnu/lib/rsbegin.o
~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-pc-windows-gnu/lib/rsend.o
```

**Comment by RalfJung** [comment]
FWIW, the PR that broke this is probably https://github.com/rust-lang/rust/pull/72999.

**Comment by Selyatin** [comment]
The pull request works. Thanks for your help.
