### ISSUE TITLE
Cross compile Tier3(mipsel-unknown-linux-uclibc) error

### ISSUE THREAD

**Issue by kolapapa** [japaric/xargo#318]
```shell
root@a5a47cd37148:/opt/build/rust_workspace/build-mipsel# xargo build --target mipsel-unknown-linux-uclibc
   Compiling build-mipsel v0.1.0 (/opt/build/rust_workspace/build-mipsel)
error: linking with `mipsel-openwrt-linux-gcc` failed: exit status: 1
  |
  = note: "mipsel-openwrt-linux-gcc" "/opt/build/rust_workspace/build-mipsel/target/mipsel-unknown-linux-uclibc/debug/deps/build_mipsel-630934868a657553.1jakxvqzos77v31h.rcgu.o" "/opt/build/rust_workspace/build-mipsel/target/mipsel-unknown-linux-uclibc/debug/deps/build_mipsel-630934868a657553.2ltib9p72qff9us7.rcgu.o" "/opt/build/rust_workspace/build-mipsel/target/mipsel-unknown-linux-uclibc/debug/deps/build_mipsel-630934868a657553.3mcar5ow98f5yb0m.rcgu.o" "/opt/build/rust_workspace/build-mipsel/target/mipsel-unknown-linux-uclibc/debug/deps/build_mipsel-630934868a657553.567445ps29h854i3.rcgu.o" "/opt/build/rust_workspace/build-mipsel/target/mipsel-unknown-linux-uclibc/debug/deps/build_mipsel-630934868a657553.frcplamj2dwfpj5.rcgu.o" "/opt/build/rust_workspace/build-mipsel/target/mipsel-unknown-linux-uclibc/debug/deps/build_mipsel-630934868a657553.gdj2d47uap3nuoq.rcgu.o" "/opt/build/rust_workspace/build-mipsel/target/mipsel-unknown-linux-uclibc/debug/deps/build_mipsel-630934868a657553.kc48hf8c1efu756.rcgu.o" "/opt/build/rust_workspace/build-mipsel/target/mipsel-unknown-linux-uclibc/debug/deps/build_mipsel-630934868a657553.x9ies61it0qyjaz.rcgu.o" "/opt/build/rust_workspace/build-mipsel/target/mipsel-unknown-linux-uclibc/debug/deps/build_mipsel-630934868a657553.22zpzpd6w1mtyi7h.rcgu.o" "-Wl,--as-needed" "-L" "/opt/build/rust_workspace/build-mipsel/target/mipsel-unknown-linux-uclibc/debug/deps" "-L" "/opt/build/rust_workspace/build-mipsel/target/debug/deps" "-L" "/root/.xargo/lib/rustlib/mipsel-unknown-linux-uclibc/lib" "-Wl,--start-group" "-Wl,-Bstatic" "/root/.xargo/lib/rustlib/mipsel-unknown-linux-uclibc/lib/libstd-5e6a27f017922099.rlib" "/root/.xargo/lib/rustlib/mipsel-unknown-linux-uclibc/lib/libpanic_abort-d39d885e282bea73.rlib" "/root/.xargo/lib/rustlib/mipsel-unknown-linux-uclibc/lib/libstd_detect-851b61686a8dd3c4.rlib" "/root/.xargo/lib/rustlib/mipsel-unknown-linux-uclibc/lib/librustc_demangle-cc20da9753c0c841.rlib" "/root/.xargo/lib/rustlib/mipsel-unknown-linux-uclibc/lib/libhashbrown-66a3107690700d29.rlib" "/root/.xargo/lib/rustlib/mipsel-unknown-linux-uclibc/lib/librustc_std_workspace_alloc-e6e02afa8a4c37f0.rlib" "/root/.xargo/lib/rustlib/mipsel-unknown-linux-uclibc/lib/libunwind-d43223cb57229def.rlib" "/root/.xargo/lib/rustlib/mipsel-unknown-linux-uclibc/lib/libcfg_if-2e0a135c818f5ff1.rlib" "/root/.xargo/lib/rustlib/mipsel-unknown-linux-uclibc/lib/liblibc-f21321e9121b1ca8.rlib" "/root/.xargo/lib/rustlib/mipsel-unknown-linux-uclibc/lib/liballoc-1634a23b28613307.rlib" "/root/.xargo/lib/rustlib/mipsel-unknown-linux-uclibc/lib/librustc_std_workspace_core-71225905b083a8b5.rlib" "/root/.xargo/lib/rustlib/mipsel-unknown-linux-uclibc/lib/libcore-66693733c9765f2d.rlib" "-Wl,--end-group" "/root/.xargo/lib/rustlib/mipsel-unknown-linux-uclibc/lib/libcompiler_builtins-bf71dc309618ac42.rlib" "-Wl,-Bdynamic" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-lutil" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/root/.xargo/lib/rustlib/mipsel-unknown-linux-uclibc/lib" "-o" "/opt/build/rust_workspace/build-mipsel/target/mipsel-unknown-linux-uclibc/debug/deps/build_mipsel-630934868a657553" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs"
  = note: /root/.xargo/lib/rustlib/mipsel-unknown-linux-uclibc/lib/libstd-5e6a27f017922099.rlib(std-5e6a27f017922099.std.4ci12uac-cgu.8.rcgu.o): In function `_$LT$std..sys_common..backtrace.._print..DisplayBacktrace$u20$as$u20$core..fmt..Display$GT$::fmt::h5c697467b8eb1224':
          std.4ci12uac-cgu.8:(.text._ZN91_$LT$std..sys_common..backtrace.._print..DisplayBacktrace$u20$as$u20$core..fmt..Display$GT$3fmt17h5c697467b8eb1224E+0x140): undefined reference to `_Unwind_Backtrace'
          std.4ci12uac-cgu.8:(.text._ZN91_$LT$std..sys_common..backtrace.._print..DisplayBacktrace$u20$as$u20$core..fmt..Display$GT$3fmt17h5c697467b8eb1224E+0x1a0): undefined reference to `_Unwind_Backtrace'
          /root/.xargo/lib/rustlib/mipsel-unknown-linux-uclibc/lib/libstd-5e6a27f017922099.rlib(std-5e6a27f017922099.std.4ci12uac-cgu.12.rcgu.o): In function `_ZN4core3ops8function6FnOnce40call_once$u7b$$u7b$vtable.shim$u7d$$u7d$17hc2a1bbcfb4ce892bE.llvm.12621699606483103073':
          std.4ci12uac-cgu.12:(.text._ZN4core3ops8function6FnOnce40call_once$u7b$$u7b$vtable.shim$u7d$$u7d$17hc2a1bbcfb4ce892bE.llvm.12621699606483103073+0x80): undefined reference to `_Unwind_GetIP'
          std.4ci12uac-cgu.12:(.text._ZN4core3ops8function6FnOnce40call_once$u7b$$u7b$vtable.shim$u7d$$u7d$17hc2a1bbcfb4ce892bE.llvm.12621699606483103073+0x84): undefined reference to `_Unwind_GetIP'
          /root/.xargo/lib/rustlib/mipsel-unknown-linux-uclibc/lib/libstd-5e6a27f017922099.rlib(std-5e6a27f017922099.std.4ci12uac-cgu.12.rcgu.o): In function `_ZN3std10sys_common9backtrace10_print_fmt28_$u7b$$u7b$closure$u7d$$u7d$17hd81ffb912cc3ae12E.llvm.12621699606483103073':
          std.4ci12uac-cgu.12:(.text._ZN3std10sys_common9backtrace10_print_fmt28_$u7b$$u7b$closure$u7d$$u7d$17hd81ffb912cc3ae12E.llvm.12621699606483103073+0x80): undefined reference to `_Unwind_GetIP'
          std.4ci12uac-cgu.12:(.text._ZN3std10sys_common9backtrace10_print_fmt28_$u7b$$u7b$closure$u7d$$u7d$17hd81ffb912cc3ae12E.llvm.12621699606483103073+0x84): undefined reference to `_Unwind_GetIP'
          collect2: error: ld returned 1 exit status


error: aborting due to previous error

error: could not compile `build-mipsel`


Caused by:
  process didn't exit successfully: `rustc --crate-name build_mipsel --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C panic=abort -C embed-bitcode=no -C debuginfo=2 -C metadata=630934868a657553 -C extra-filename=-630934868a657553 --out-dir /opt/build/rust_workspace/build-mipsel/target/mipsel-unknown-linux-uclibc/debug/deps --target mipsel-unknown-linux-uclibc -C linker=mipsel-openwrt-linux-gcc -C incremental=/opt/build/rust_workspace/build-mipsel/target/mipsel-unknown-linux-uclibc/debug/incremental -L dependency=/opt/build/rust_workspace/build-mipsel/target/mipsel-unknown-linux-uclibc/debug/deps -L dependency=/opt/build/rust_workspace/build-mipsel/target/debug/deps --sysroot /root/.xargo` (exit status: 1)
```

Another issue https://github.com/rust-lang/rust/issues/86168

**Comment by kolapapa** [comment]
> ```shell
> root@a5a47cd37148:/opt/build/rust_workspace/build-mipsel# xargo build --target mipsel-unknown-linux-uclibc
>    Compiling build-mipsel v0.1.0 (/opt/build/rust_workspace/build-mipsel)
> error: linking with `mipsel-openwrt-linux-gcc` failed: exit status: 1
>   |
>   = note: "mipsel-openwrt-linux-gcc" "/opt/build/rust_workspace/build-mipsel/target/mipsel-unknown-linux-uclibc/debug/deps/build_mipsel-630934868a657553.1jakxvqzos77v31h.rcgu.o" "/opt/build/rust_workspace/build-mipsel/target/mipsel-unknown-linux-uclibc/debug/deps/build_mipsel-630934868a657553.2ltib9p72qff9us7.rcgu.o" "/opt/build/rust_workspace/build-mipsel/target/mipsel-unknown-linux-uclibc/debug/deps/build_mipsel-630934868a657553.3mcar5ow98f5yb0m.rcgu.o" "/opt/build/rust_workspace/build-mipsel/target/mipsel-unknown-linux-uclibc/debug/deps/build_mipsel-630934868a657553.567445ps29h854i3.rcgu.o" "/opt/build/rust_workspace/build-mipsel/target/mipsel-unknown-linux-uclibc/debug/deps/build_mipsel-630934868a657553.frcplamj2dwfpj5.rcgu.o" "/opt/build/rust_workspace/build-mipsel/target/mipsel-unknown-linux-uclibc/debug/deps/build_mipsel-630934868a657553.gdj2d47uap3nuoq.rcgu.o" "/opt/build/rust_workspace/build-mipsel/target/mipsel-unknown-linux-uclibc/debug/deps/build_mipsel-630934868a657553.kc48hf8c1efu756.rcgu.o" "/opt/build/rust_workspace/build-mipsel/target/mipsel-unknown-linux-uclibc/debug/deps/build_mipsel-630934868a657553.x9ies61it0qyjaz.rcgu.o" "/opt/build/rust_workspace/build-mipsel/target/mipsel-unknown-linux-uclibc/debug/deps/build_mipsel-630934868a657553.22zpzpd6w1mtyi7h.rcgu.o" "-Wl,--as-needed" "-L" "/opt/build/rust_workspace/build-mipsel/target/mipsel-unknown-linux-uclibc/debug/deps" "-L" "/opt/build/rust_workspace/build-mipsel/target/debug/deps" "-L" "/root/.xargo/lib/rustlib/mipsel-unknown-linux-uclibc/lib" "-Wl,--start-group" "-Wl,-Bstatic" "/root/.xargo/lib/rustlib/mipsel-unknown-linux-uclibc/lib/libstd-5e6a27f017922099.rlib" "/root/.xargo/lib/rustlib/mipsel-unknown-linux-uclibc/lib/libpanic_abort-d39d885e282bea73.rlib" "/root/.xargo/lib/rustlib/mipsel-unknown-linux-uclibc/lib/libstd_detect-851b61686a8dd3c4.rlib" "/root/.xargo/lib/rustlib/mipsel-unknown-linux-uclibc/lib/librustc_demangle-cc20da9753c0c841.rlib" "/root/.xargo/lib/rustlib/mipsel-unknown-linux-uclibc/lib/libhashbrown-66a3107690700d29.rlib" "/root/.xargo/lib/rustlib/mipsel-unknown-linux-uclibc/lib/librustc_std_workspace_alloc-e6e02afa8a4c37f0.rlib" "/root/.xargo/lib/rustlib/mipsel-unknown-linux-uclibc/lib/libunwind-d43223cb57229def.rlib" "/root/.xargo/lib/rustlib/mipsel-unknown-linux-uclibc/lib/libcfg_if-2e0a135c818f5ff1.rlib" "/root/.xargo/lib/rustlib/mipsel-unknown-linux-uclibc/lib/liblibc-f21321e9121b1ca8.rlib" "/root/.xargo/lib/rustlib/mipsel-unknown-linux-uclibc/lib/liballoc-1634a23b28613307.rlib" "/root/.xargo/lib/rustlib/mipsel-unknown-linux-uclibc/lib/librustc_std_workspace_core-71225905b083a8b5.rlib" "/root/.xargo/lib/rustlib/mipsel-unknown-linux-uclibc/lib/libcore-66693733c9765f2d.rlib" "-Wl,--end-group" "/root/.xargo/lib/rustlib/mipsel-unknown-linux-uclibc/lib/libcompiler_builtins-bf71dc309618ac42.rlib" "-Wl,-Bdynamic" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-lutil" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/root/.xargo/lib/rustlib/mipsel-unknown-linux-uclibc/lib" "-o" "/opt/build/rust_workspace/build-mipsel/target/mipsel-unknown-linux-uclibc/debug/deps/build_mipsel-630934868a657553" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs"
>   = note: /root/.xargo/lib/rustlib/mipsel-unknown-linux-uclibc/lib/libstd-5e6a27f017922099.rlib(std-5e6a27f017922099.std.4ci12uac-cgu.8.rcgu.o): In function `_$LT$std..sys_common..backtrace.._print..DisplayBacktrace$u20$as$u20$core..fmt..Display$GT$::fmt::h5c697467b8eb1224':
>           std.4ci12uac-cgu.8:(.text._ZN91_$LT$std..sys_common..backtrace.._print..DisplayBacktrace$u20$as$u20$core..fmt..Display$GT$3fmt17h5c697467b8eb1224E+0x140): undefined reference to `_Unwind_Backtrace'
>           std.4ci12uac-cgu.8:(.text._ZN91_$LT$std..sys_common..backtrace.._print..DisplayBacktrace$u20$as$u20$core..fmt..Display$GT$3fmt17h5c697467b8eb1224E+0x1a0): undefined reference to `_Unwind_Backtrace'
>           /root/.xargo/lib/rustlib/mipsel-unknown-linux-uclibc/lib/libstd-5e6a27f017922099.rlib(std-5e6a27f017922099.std.4ci12uac-cgu.12.rcgu.o): In function `_ZN4core3ops8function6FnOnce40call_once$u7b$$u7b$vtable.shim$u7d$$u7d$17hc2a1bbcfb4ce892bE.llvm.12621699606483103073':
>           std.4ci12uac-cgu.12:(.text._ZN4core3ops8function6FnOnce40call_once$u7b$$u7b$vtable.shim$u7d$$u7d$17hc2a1bbcfb4ce892bE.llvm.12621699606483103073+0x80): undefined reference to `_Unwind_GetIP'
>           std.4ci12uac-cgu.12:(.text._ZN4core3ops8function6FnOnce40call_once$u7b$$u7b$vtable.shim$u7d$$u7d$17hc2a1bbcfb4ce892bE.llvm.12621699606483103073+0x84): undefined reference to `_Unwind_GetIP'
>           /root/.xargo/lib/rustlib/mipsel-unknown-linux-uclibc/lib/libstd-5e6a27f017922099.rlib(std-5e6a27f017922099.std.4ci12uac-cgu.12.rcgu.o): In function `_ZN3std10sys_common9backtrace10_print_fmt28_$u7b$$u7b$closure$u7d$$u7d$17hd81ffb912cc3ae12E.llvm.12621699606483103073':
>           std.4ci12uac-cgu.12:(.text._ZN3std10sys_common9backtrace10_print_fmt28_$u7b$$u7b$closure$u7d$$u7d$17hd81ffb912cc3ae12E.llvm.12621699606483103073+0x80): undefined reference to `_Unwind_GetIP'
>           std.4ci12uac-cgu.12:(.text._ZN3std10sys_common9backtrace10_print_fmt28_$u7b$$u7b$closure$u7d$$u7d$17hd81ffb912cc3ae12E.llvm.12621699606483103073+0x84): undefined reference to `_Unwind_GetIP'
>           collect2: error: ld returned 1 exit status
> 
> 
> error: aborting due to previous error
> 
> error: could not compile `build-mipsel`
> 
> 
> Caused by:
>   process didn't exit successfully: `rustc --crate-name build_mipsel --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C panic=abort -C embed-bitcode=no -C debuginfo=2 -C metadata=630934868a657553 -C extra-filename=-630934868a657553 --out-dir /opt/build/rust_workspace/build-mipsel/target/mipsel-unknown-linux-uclibc/debug/deps --target mipsel-unknown-linux-uclibc -C linker=mipsel-openwrt-linux-gcc -C incremental=/opt/build/rust_workspace/build-mipsel/target/mipsel-unknown-linux-uclibc/debug/incremental -L dependency=/opt/build/rust_workspace/build-mipsel/target/mipsel-unknown-linux-uclibc/debug/deps -L dependency=/opt/build/rust_workspace/build-mipsel/target/debug/deps --sysroot /root/.xargo` (exit status: 1)
> ```
> 
> Another issue [rust-lang/rust#86168](https://github.com/rust-lang/rust/issues/86168)

I tried the next old version，` rustup toolchain install nightly-2020-08-26`, compiled successfully.

```shell
root@a5a47cd37148:/opt/build/rust_workspace/build-mipsel# xargo build --target mipsel-unknown-linux-uclibc
   Compiling build-mipsel v0.1.0 (/opt/build/rust_workspace/build-mipsel)
    Finished dev [unoptimized + debuginfo] target(s) in 0.32s
root@a5a47cd37148:/opt/build/rust_workspace/build-mipsel# rustup -Vv
rustup 1.24.3 (ce5817a94 2021-05-31)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.47.0-nightly (2d8a3b918 2020-08-26)`
```

Is there anything compatible with the new version?

**Comment by RalfJung** [comment]
Are you using the latest xargo, v0.3.23?

If someone can figure out what is going on, I'd be happy to review a PR, but xargo is not being developed any more and I don't know anything about cross-compiling so I am afraid I can't be of much help jere.

**Comment by kolapapa** [comment]
> Are you using the latest xargo, v0.3.23?
```shell
#  nightly-x86_64-unknown-linux-gnu  && build failed
root@a5a47cd37148:/opt/build/rust_workspace/build-mipsel# xargo --version
xargo 0.3.23
cargo 1.54.0-nightly (0cecbd673 2021-06-01)

# nightly-2020-08-27-x86_64-unknown-linux-gnu && build success
root@a5a47cd37148:/opt/build/rust_workspace/build-mipsel# xargo --version
xargo 0.3.23
cargo 1.47.0-nightly (51b66125b 2020-08-19)
```

**Comment by kolapapa** [comment]
cargo `build-std` can solve
