### ISSUE TITLE
Cargo cannot build `compiler_builtins` for `aarch64-unknown-linux-musl`

### ISSUE THREAD

**Issue by littlebenlittle** [japaric/xargo#320]
_Full example on [this branch](https://github.com/littlebenlittle/wry-aarch64-musl-example/tree/xargo)_

I'm trying to build a [tauri-apps/wry](https://github.com/tauri-apps/wry) example for `aarch64-unknown-linux-musl`. My build container errors out, however.

The gist of the build is

```sh
ctr=`buildah from docker.io/library/rust:1.53-alpine3.13`
buildah run $ctr apk add \
	gtk+3.0 \
	webkit2gtk-dev \
	gtksourceview-dev
buildah add $ctr $LOCAL/aarch64-linux-musl-cross /opt/aarch64-linux-musl-cross
buildah run $ctr rustup target add aarch64-unknown-linux-musl
buildah run $ctr cargo install xargo
buildah run $ctr rustup default nightly
buildah run $ctr rustup component add rust-src
buildah commit $ctr webkit-aarch64
podman run -ti --rm \
	--name rs \
	-v ./:/mnt \
	-w /mnt \
	-e RUST_BACKTRACE=1 \
	localhost/webkit-aarch64 xargo build --target=aarch64-unknown-linux-musl --verbose

```

This results in

```
...
error: failed to parse manifest at `/tmp/xargo.yFwNkG10hwg9/Cargo.toml`

Caused by:
  dependency (compiler_builtins) specified without providing a local path, Git repository, or version to use.
error: `"cargo" "build" "--release" "--manifest-path" "/tmp/xargo.yFwNkG10hwg9/Cargo.toml" "--target" "aarch64-unknown-linux-musl" "-v" "-p" "compiler_builtins"` failed with exit code: Some(101)
...
```

~A challenge here is that the temporary Cargo.toml gets cleaned up xargo.~

> you can set XARGO_KEEP_TEMP to disable the cleanup -- @RalfJung

**Comment by RalfJung** [comment]
I probably can't help much with your actual problem, but...

> A challenge here is that the temporary Cargo.toml gets cleaned up xargo.

you can set `XARGO_KEEP_TEMP` to disable the cleanup.

It sounds like there might be a `compiler_builtins` but the crate does not exist for this architecture, or cannot be found in the sysroot source?

**Comment by littlebenlittle** [comment]
Looks like `compiler_builtins` is installed [by default](https://github.com/japaric/xargo/blob/b64ed6614fd7578de3b7893538d63f4f23e3522f/src/sysroot.rs#L538).

It seems strange that rust is complaining that the version isn't specified.

**Comment by Am3ra** [comment]
hmm, getting the same issue with a new project, almost empty, and have no Idea why. 

For reference, these are the steps I'm taking to reproduce:

https://wiki.osdev.org/Raspberry_Pi_Bare_Bones_Rust

**Comment by RalfJung** [comment]
The same error also appears in https://github.com/japaric/xargo/pull/321 during CI, so there's definitely some rustc/cargo change that happened here. But I won't have time to look into this for now... help would be much appreciated!

**Comment by anickol** [comment]
Is it because of the missing source for `compiler_builtins` in rust-src? I am not sure if it had been there before.

ln `~/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library` there is no `compiler_builtins` folder.

By adding `git = "https://github.com/rust-lang/compiler-builtins"` to the Cargo.toml of the problematic build, the build takes on.

**Comment by anickol** [comment]
I created a patch that adds the git reference, but I'm not sure what the previous behavior was.
