### ISSUE TITLE
`xargo doc` doesn't seem to work

### ISSUE THREAD

**Issue by cbiffle** [japaric/xargo#42]
Xargo is working fabulously for my embedded project, with one exception.

```
[cbiffle@anansi emb1]$ xargo build --release
    Finished release [optimized + debuginfo] target(s) in 0.0 secs
[cbiffle@anansi emb1]$ xargo doc --release
 Documenting bitflags v0.7.0
error[E0463]: can't find crate for `core`

error: aborting due to previous error

error: Could not document `bitflags`.

To learn more, run the command again with --verbose.
error: `cargo` process didn't exit successfully
```

`xargo doc` doesn't seem to be hunting for crates in the sysroot.  Am I doing something wrong?

**Comment by japaric** [comment]
Interesting, I don't think I ever tested this :P. I think there are two problems here:

- For `xargo build`, we inform `rustc` about Xargo's sysroot via the `--sysroot` flag. This flag is passed to all the `rustc` invocations via the RUSTFLAGS env variable. `rustdoc` has a similar flag: RUSTDOCFLAGS but we are not setting it. This we can fix in Xargo.
- `rustdoc` doesn't have a `--sysroot` flag so we can't tell it about the Xargo sysroot. This would have to be fixed upstream.

**Comment by japaric** [comment]
@cbiffle BTW, does `cargo doc` (with target = host) work in your case?

This works for me:

``` rust
#![feature(asm)]

pub fn bkpt() {
    unsafe {
        asm!("bkpt");
    }
}
```

```
$ rustc -Vv | grep host
host: x86_64-unknown-linux-gnu
$ cargo doc --target x86_64-unknown-linux-gnu
```

(`cargo build --target x86_64-unknown-linux-gnu` errors though)

It could be a temporary workaround.

**Comment by cbiffle** [comment]
Nope, and I'm not sure why:

```
$ cargo doc --target x86_64-unknown-linux-gnu
   Compiling bitflags v0.7.0
 Documenting emb v0.1.0 (file:///home/cbiffle/proj/rs/emb1/lib)
   Compiling emb v0.1.0 (file:///home/cbiffle/proj/rs/emb1/lib)
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

thread 'rustc' panicked at 'index out of bounds: the len is 0 but the index is 218', ../src/libcollections/vec.rs:1307
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: Could not compile `emb`.

To learn more, run the command again with --verbose.
error: `cargo` process didn't exit successfully
```

**Comment by japaric** [comment]
> thread 'rustc' panicked at 'index out of bounds: the len is 0 but the index is 218'

That looks like rust-lang/rust#35422. Do you have `asm!` behind a macro?

**Comment by cbiffle** [comment]
I do, I'll post the rustc backtrace on that bug.
