### ISSUE TITLE
Failed to compile xargo

### ISSUE THREAD

**Issue by Kixunil** [japaric/xargo#63]
[Output](http://pastebin.com/titM3LKU)

System: Linux Mint Maya (Mate edition)
I've installed both cmake and libssl-dev

Any idea wha could be wrong?

**Comment by japaric** [comment]
>   CMake 2.8.11 or higher is required.  You are running version 2.8.7

This probably. Any chance you could try with a newer cmake release? Otherwise, there are also [binary releases](https://github.com/japaric/xargo/releases) available; would those work for you?

**Comment by Kixunil** [comment]
I missed that line in output but it actually wasn't the problem. I looked just at `sudo apt-get install cmake libssl-dev` line and missed `sudo apt-get install libcurl4-openssl-dev libssh2-1-dev
`. After installing `libssh2-1-dev`, it compiled and installed. I'm going to try it.

I'm not sure whether it's my tiredness or the README could be made more clear...

Anyway, I'm sorry for such trivial issue.
