### ISSUE TITLE
Make Xargo use an existing local Rust source repository

### ISSUE THREAD

**Issue by nabeelomer** [japaric/xargo#66]
Instead of downloading a new source code tarball, maybe something like `xargo --rust-source-path=~/src/rust ...` can be used.

**Comment by japaric** [comment]
As of #65 Xargo now depends on the `rust-src` component that `rustup` can install. Xargo no longer downloads anything by itself.

Does that cover your use case? Or is your use case related to the "dev" channel? If the latter, we could add use a `XARGO_RUST_SRC` env variable to tell Xargo where to find the source of the current "dev" compiler.

**Comment by nabeelomer** [comment]
It is the latter.

**Comment by NilSet** [comment]
Racer already uses the `RUST_SRC_PATH` env variable to find the source, I think it would make sense to use that.

**Comment by japaric** [comment]
Done in #94
