### ISSUE TITLE
Xargo modifies the contents of `rust-src`

### ISSUE THREAD

**Issue by japaric** [japaric/xargo#82]
because it uses the `cargo metadata` under the hood and that places a `Cargo.lock` in `src/libstd`. Unsure how bad this actually is. My next `rustup update` will probably answer that.

**Comment by est31** [comment]
@japaric I haven't tried it, but maybe this can be fixed by passing `--locked` or `--frozen` to the cargo command.

**Comment by RalfJung** [comment]
This does not seem to happen any more. At least, the only `Cargo.lock` I can see is the one in the root. I also did a diff to ensure that the rust-src dir is not changed.
