### ISSUE TITLE
No compiler_builtins for no_std builds?

### ISSUE THREAD

**Issue by jdub** [japaric/xargo#90]
Hey there! `compiler_builtins` doesn't appear to be built for a `no_std` sysroot. It turns up in `~/.xargo/lib/rustlib/x86_64-unknown-linux-gnu/lib/` along with the rest of std though.

From a quick glance at the code, I can't figure out why it's not built. It's a dependency of `libstd`, and I can't see where that list is being filtered. (It's clearly not tested in `tests/smoke.rs` though.)

When I was making sysroots with a cheesy script instead of xargo, it built fine and often came in handy.

**Comment by japaric** [comment]
The latest stable release of Xargo only compiles [a few crates](https://github.com/japaric/xargo/blob/v0.2.1/src/sysroot.rs#L40-L44). Notably, compiler-builtins is not there.

The latest git version should compile everything beneath std including std. Does that version not try to compile compiler-builtins?

Alternatively, you could depend on [rust-lang-nursery/compiler-builtins](https://github.com/rust-lang-nursery/compiler-builtins) it contains a few compiler-rt intrinsics that have been ported to Rust but it also provides an opt-in "c" Cargo features that compiles compiler-rt to get the full collection of intrinsics.

**Comment by jdub** [comment]
\*facepalm\* Silly me, I was reading master while using the latest release! master does indeed build compiler-builtins, and all is well. Thank you and apologies for the interruption. 😄
