### ISSUE TITLE
Doesn't build alloc and collections when max_atomic_width = 0

### ISSUE THREAD

**Issue by thejpster** [japaric/xargo#91]
I believe alloc now builds for thumbv6 (max_atomic_width=0), so could xargo now build alloc and collections?

I looked in the source code but I couldn't see where the builds where elided. Is it actually something cargo does?

Edit: Apologies for the edits - my finger slipped :/

**Comment by japaric** [comment]
Not a Xargo issue but should be fixed when rust-lang/rust#37492 makes its way into a nightly. Today, maybe?

**Comment by thejpster** [comment]
Ah, I thought that had made it in already.

**Comment by japaric** [comment]
Might want to try Xargo HEAD as well, not the stable release.

**Comment by japaric** [comment]
(`cargo install --git https://github.com/japaric/xargo`)

**Comment by thejpster** [comment]
Yeah, I already have that forked and checked out ;)

Right, I can see xargo head does now attempt to build alloc - that explains why I couldn't find the code that blocked it in the source code for head. And building alloc fails, so I probably need to wait another day or so for nightly to churn.

Closed: Not an issue
